#! /usr/bin/env bash

#  $Header: /u/gcmpack/MITgcm/verification/global_ocean.cs32x15/input_ad/prepare_run,v 1.1 2008/06/14 16:58:31 heimbach Exp $
#  $Name:  $
 
#- in order to save disc space, take files:
fileList="grid_cs32.face001.bin grid_cs32.face002.bin grid_cs32.face003.bin grid_cs32.face004.bin grid_cs32.face005.bin grid_cs32.face006.bin"

#- from this dir:
fromDir="../../tutorial_held_suarez_cs/input"

#- and do a symbolic link in the current directory 
#   (if the file does not already exist)
if test -d $fromDir ; then
  lnkList='files:'
  for xx in $fileList
  do
    if test -r ${fromDir}/$xx ; then 
      if test ! -r $xx ; then 
        lnkList=${lnkList}" "$xx
        ln -sf ${fromDir}/$xx .
      fi
    fi
  done
  echo ' link' $lnkList "from dir:" $fromDir
else
  echo " Error:" $fromDir "not a directory"
fi
