/*  Warning - this file is automatically generated - do NOT edit  */
/*
 Created by convert_cpp_cmd2defines with the following command line arguments:
 Forward version -bAD_CONFIG_H -UALLOW_ADJOINT_RUN -UALLOW_TANGENTLINEAR_RUN
*/

/*  Forward version  */
#ifndef AD_CONFIG_H
#define AD_CONFIG_H
#undef  ALLOW_ADJOINT_RUN
#undef  ALLOW_TANGENTLINEAR_RUN
#endif /* AD_CONFIG_H */
