#! /usr/bin/env bash

#  $Header: /u/gcmpack/MITgcm/verification/isomip/input.htd/Attic/prepare_run,v 1.1 2015/02/15 14:11:49 mlosch Exp $
#  $Name:  $

#- in order to save disc space, take *.bin files
#- from this dir:
fromDir="../input_ad"

fileList=`( cd $fromDir ; ls pickup*.0000008640.??ta )`

#echo 'fileList=' $fileList

#- and do a symbolic link in the current directory
#   (if the file does not already exist)
if test -d $fromDir ; then
  lnkList='files:'
  for xx in $fileList
  do
    if test -r ${fromDir}/$xx ; then
      if test ! -r $xx ; then
        lnkList=${lnkList}" "$xx
        ln -sf ${fromDir}/$xx .
      fi
    fi
  done
  echo ' link' $lnkList "from dir:" $fromDir
else
  echo " Error:" $fromDir "not a directory"
fi
