#!/bin/bash
# This is a shell script to combine multiple MITgcm mnc output files from 
# different tiles into one global file.
# All of the variables should be in one directory, where this script is run.
#
# To combine all state.0000000000.t*.nc files,
#  gluemnc state.0000000000.*.nc 
# This will result in an output file state.0000000000.glob.nc 
# Where glob is for global.
#
# You can even combine all mnc files, use
#  gluemnc *.nc
# This will result in a series of global files,
# state.0000000000.glob.nc state.0000000100.glob.nc, ...
# grid.0000000000.glob.nc grid.0000000100.glob.nc, ...
# diag.0000000000.glob.nc diag.0000000100.glob.nc, ...
#
# A lot of hard drive activity is needed.  If you have a fast drive
# export TMPDIR=<path of hard drive>.  On some high-performance 
# systems, this is already done for you.
#
# **********WARNINGS**********
# This will probably not work at all with exch2/cubed sphere.
# In that case, you probably can assemble all of the tiles on a face,
# but combining faces is currently not implemented.
#
# Be sure you have enough disk space for the copies!  In this version
# nothing is done to assure all of the data is copied.
#
# Be careful!  It will be easy to exceed the 2 GB limit for the old 32-bit
# version of netcdf.  If you do not have large-file support or 64-bit netcdf
# you will have to be clever in dividing up your tiled files,
# e.g., along the time dimension before combining to global files.
# The nco operator ncks is adept at shortening files to fewer snapshots.
# *****************************
#
# Good luck and happy gluing,
# Baylor Fox-Kemper

DEBUG="--dbg_lvl=0"
LOGFILE="/dev/null"

DIRORIG=`pwd`

if [ ! ${#TMPDIR} -gt 0 ]; then
  TMPDIR=$DIRORIG
fi

export DIRNAME="$TMPDIR/gluedir.$RANDOM"
mkdir $DIRNAME

echo Using temporary directory $DIRNAME

if [ -f xplodemnc ]; then
 cp xplodemnc $DIRNAME
else
 cp `which xplodemnc` $DIRNAME
fi

cd $DIRNAME

inone=$1
inone=${1:?"You must input mnc filenames to be glued"}

for somefile in $@
do
  ln -s $DIRORIG/$somefile .
  if [ ! -s $somefile ]; then
    echo "Error: $somefile is missing or empty"
    exit 1
  fi
done

prels=${@%.t???.nc}

for somepre in $prels
do
  inls=0
  for somepres in $sprels
  do
    if [ "$somepre" = "$somepres" ]; then
      inls=1
    fi
  done
  if [ "$inls" = "0" ]; then
   sprels=$sprels" "$somepre
  fi
done

prels=$sprels

# ML: determine the coordinate variable (this is hack for the unlikely
# case that we do not have X or Y as coordinate variables; this can
# happen, when only U-point or V-point variables are written to a
# diagnostics stream; I do not know if this always works, but it works for me)
echo Determine a usable coordinate variable
somefile=${prels}.t001.nc
# first try X and Y
Xcoord=X
Ycoord=Y
Xtest=$(ncdump -vX -l 10000 $somefile | grep "X = ")
Ytest=$(ncdump -vY -l 10000 $somefile | grep "Y = ")
if [ ${#Xtest} = 0 ]; then
    echo "X not found, trying Xp1"
    Xtest=$(ncdump -vXp1 -l 10000 $somefile | grep "Xp1 = ")
    Xcoord=Xp1
fi
if [ ${#Xtest} = 0 ]; then
    echo "no X-coordinate found"
    Xcoord=
fi
if [ ${#Ytest} = 0 ]; then
    echo "Y not found, trying Yp1"
    Ytest=$(ncdump -vYp1 -l 10000 $somefile | grep "Yp1 = ")
    Ycoord=Yp1
fi
if [ ${#Ytest} = 0 ]; then
    echo "no Y-coordinate found"
    Ycoord=
fi
if [ ${#Xcoord} = 0 ]; then
    echo cannot continue
    exit
fi
if [ ${#Ycoord} = 0 ]; then
    echo cannot continue
    exit
fi

for somepre in $prels
do
  echo Making $somepre.glob.nc...
  Xsls=
  Ysls=

  for somefile in $@
  do
    if [ "${somefile%.t???.nc}" = "$somepre" ]; then
      echo Scanning $somefile...
      Xs=$(ncdump -v${Xcoord} -l 10000 $somefile | grep "${Xcoord} = ")
      Xs=${Xs#*;}
      Xs=${Xs%;*}
      Xs=$(echo $Xs | sed s/' '//g)
      Xsls=$Xsls$Xs" "

      Ys=$(ncdump -v${Ycoord} -l 10000 $somefile | grep "${Ycoord} = ")
      Ys=${Ys#*;}
      Ys=${Ys%;*}
      Ys=$(echo $Ys | sed s/' '//g)
      Ysls=$Ysls$Ys" "
    fi
  done

  sYsls=
  sXsls=

  # Determine all the X locations
  countx=0
  for someXs in $Xsls
  do 
    inls=0
    for somesXs in $sXsls
    do
      if [ "$someXs" = "$somesXs" ]; then
        inls=1
      fi
    done
    if [ "$inls" = "0" ]; then
      sXsls=$sXsls$someXs" "
      countx=$((countx))+1
    fi
  done
  echo XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  echo $((countx)) tiles found in x-direction.
  echo XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  # Determine all the Y locations
  county=0
  for someYs in $Ysls
  do 
    inls=0
    for somesYs in $sYsls
    do
      if [ "$someYs" = "$somesYs" ]; then
        inls=1
      fi
    done
    if [ "$inls" = "0" ]; then
      sYsls=$sYsls$someYs" "
      county=$((county))+1
    fi
  done
  echo YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
  echo $((county)) tiles found in y-direction.
  echo YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY

  countyy=1000
  countxx=1000

  cntls=
  for someX in $sXsls
  do
    countxx=$((countxx+1))
    cntls=$cntls$countxx" "
    echo XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    echo  Prepping X tile $((countxx-1000))
    echo XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    for somefile in $@
    do
      if [ "${somefile%.t???.nc}" = "$somepre" ]; then
        Xs=$(ncdump -v${Xcoord} -l 10000 $somefile | grep "${Xcoord} = ")
        Xs=${Xs#*;}
        Xs=${Xs%;*}
        Xs=$(echo $Xs | sed s/' '//g)

        if [ "$someX" = $Xs ]; then
          ./xplodemnc $somefile 
          mv iter.$somefile iter.${somefile%t???.nc}glob.nc
          for somesplit in $(ls *.$somefile)
          do
            withY=$(ncdump -h $somesplit | grep "Y =")
            if [ ${#withY} -gt 1 ]; then
              echo Changing Y to record variable in $somesplit
              ncpdq $DEBUG -O -a Y,T $somesplit $somesplit > $LOGFILE
              mv $somesplit $countxx.$somesplit
            fi
            
            if [ -f $somesplit ]; then
              withYp1=$(ncdump -h $somesplit | grep "Yp1 =")
              if [ ${#withYp1} -gt 1 ]; then
                Yp1len=${withYp1#*= }
                Yp1len=$((${Yp1len% ;}-1))
                #  Strip off the repeated value in Yp1
                echo Changing Yp1 to record variable in $somesplit
                ncpdq $DEBUG -O -a Yp1,T -F -d Yp1,1,$Yp1len $somesplit $somesplit > $LOGFILE
                mv $somesplit $countxx.$somesplit
              fi
            fi
          done
        fi
      fi
    done
  done
  echo Tile names $cntls
  for countxx in $cntls
  do
    echo XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    echo  Combining X tile $((countxx-1000))
    echo XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    varls=
    cxfilels=$(ls $countxx.*)
    oldvar=
    for somefile in $cxfilels
    do
      varname=${somefile%.*}
      varname=${varname%.*}
      varname=${varname%.*}
      varname=${varname%.*}
      varname=${varname#*.}
      if [ "$varname" = "$oldvar" ]; then
        echo $varname repeated
      else
        varls=$varls$varname" "
      fi
      oldvar=$varname
    done

    echo Found these variables to combine: $varls

    for somevar in $varls
    do
      echo YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
      echo Combining $somevar files in Y
      echo YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY

      withY=$(ncdump -h $countxx.$somevar.$somepre.*.nc | grep "Y =")
      withYp1=$(ncdump -h $countxx.$somevar.$somepre.*.nc | grep "Yp1 =")

      ncrcat $DEBUG $countxx.$somevar.$somepre.*.nc $somevar.$somepre.gloy.$countxx.nc > $LOGFILE
      echo Just combined $countxx.$somevar
      rm $countxx.$somevar.$somepre.t???.nc

      if [ ${#withY} -gt 1 ]; then
        echo Changing T to record variable in $somevar.$somepre.gloy.$countxx.nc
        ncpdq $DEBUG -O -a T,Y $somevar.$somepre.gloy.$countxx.nc $somevar.$somepre.gloy.$countxx.nc > $LOGFILE
      fi

      if [ ${#withYp1} -gt 1 ]; then
        echo Changing T to record variable in $somevar.$somepre.gloy.$countxx.nc
        ncpdq $DEBUG -O -a T,Yp1 $somevar.$somepre.gloy.$countxx.nc $somevar.$somepre.gloy.$countxx.nc > $LOGFILE
      fi
    done
  done
  for somevar in $varls
  do
    echo XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    echo Combining $somevar files in X...
    echo XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    for somegloy in $(ls $somevar.$somepre.gloy.*.nc)
    do
      withX=$(ncdump -h $somegloy | grep "X =")
      withXp1=$(ncdump -h $somegloy | grep "Xp1 =")
 
      if [ ${#withX} -gt 1 ]; then
        echo Changing X to record variable in $somegloy
        ncpdq $DEBUG -O -a X,T $somegloy $somegloy > $LOGFILE
      fi

      if [ ${#withXp1} -gt 1 ]; then
        Xp1len=${withXp1#*= }
        Xp1len=$((${Xp1len% ;}-1))
        #  Strip off the repeated value in Xp1
        echo Changing Xp1 to record variable in $somegloy
echo   ncpdq $DEBUG -O -a Xp1,T -F -d Xp1,1,$Xp1len $somegloy $somegloy > $LOGFILE
        ncpdq $DEBUG -O -a Xp1,T -F -d Xp1,1,$Xp1len $somegloy $somegloy > $LOGFILE
      fi
    done
    echo Combining $somevar.gloy files...
    ncrcat $DEBUG $somevar.$somepre.gloy.*.nc $somevar.$somepre.glob.nc > $LOGFILE
#    rm $somevar.$somepre.gloy.*.nc

    if [ ${#withX} -gt 1 ]; then
      echo Changing T to record variable in $somevar.$somepre.glob.nc
      ncpdq $DEBUG -O -a T,X $somevar.$somepre.glob.nc $somevar.$somepre.glob.nc > $LOGFILE
    fi

    if [ ${#withXp1} -gt 1 ]; then
      echo Changing T to record variable in $somevar.$somepre.glob.nc
      ncpdq $DEBUG -O -a T,Xp1 $somevar.$somepre.glob.nc $somevar.$somepre.glob.nc > $LOGFILE
    fi
  ncrcat $DEBUG -A $somevar.$somepre.glob.nc $somepre.glob.nc > $LOGFILE
#  rm $somevar.$somepre.glob.nc
  done
  ncrcat $DEBUG -A iter.$somepre.glob.nc $somepre.glob.nc > $LOGFILE
#  rm iter.$somepre.glob.nc

  cp $somepre.glob.nc $DIRORIG
done


cd $DIRORIG
rm -rf $DIRNAME

