#!/bin/bash

# $Header: /u/gcmpack/MITgcm/verification/ideal_2D_oce/input/Attic/gm_local,v 1.1 2003/08/16 14:01:09 edhill Exp $

#  This is the local options file for the "new" version of genmake 
#
#  EH3 initial version 2003-08


DISABLE="aim kpp shap_filt obcs zonal_filt"

