#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/Attic/ames_dbg+mpi,v 1.2 2003/08/27 22:12:31 edhill Exp $
#

S64='$(TOOLSDIR)/set64bitConst.sh'
MAKEDEPEND=makedepend
DEFINES='-DWORDLENGTH=4'


INCLUDES='-I/usr/include -I/opt/mpt/1.6.1.beta/usr/include'
FFLAGS='-n32 -extend_source -bytereclen'
LIBS='-lmpi -lscs'
FC='f90'
LINK='f90'
