#!/bin/bash
#
# $Header: /u/gcmpack/MITgcm/tools/build_options/darwin_ia32_g95,v 1.3 2010/03/21 22:22:52 jmc Exp $
# $Name:  $

# tested on MacBook Pro
# on 28-Nov-2006

CPP='/usr/bin/cpp -traditional -P'
FC=g95
CC=gcc
LINK=g95
NOOPTFLAGS='-O0'

S64='$(TOOLSDIR)/set64bitConst.sh'
#EH3 MAKEDEPEND='${TOOLSDIR}/xmakedepend'
#EH3 MAKEDEPEND=makedepend
DEFINES='-D_BYTESWAPIO -DWORDLENGTH=4'
INCLUDEDIRS='/sw/include'
INCLUDES='-I/sw/include'
LIBS='-L/sw/lib -lnetcdf'
###FC_NAMEMANGLE="#define FC_NAMEMANGLE(X) _ ## X"
###FC_NAMEMANGLE="#define FC_NAMEMANGLE(X) X"
###FC_NAMEMANGLE="#define FC_NAMEMANGLE(X) X ## _"

#  For IEEE, use the "-ffloat-store" option
if test "x$IEEE" = x ; then
    FFLAGS='-Wunused -Wuninitialized'
    FOPTIM='-O3 -funroll-loops'
else
    FFLAGS='-Wunused -ffloat-store'
    FOPTIM='-O0'
fi


