#!/bin/bash

# $Header: /u/gcmpack/MITgcm/tools/build_options/darwin_ppc_g77,v 1.5 2006/02/13 13:11:19 mlosch Exp $
#
# tested on G4-PowerBook, 1GHz
# cc-compiler is available only with the Apple Developer Tools, 
# so make sure that those are installed 
# g77 can be optained from FINK: http://fink.sourceforge.net
#

CPP='/usr/bin/cpp -traditional -P'
FC=g77
LINK=g77
NOOPTFLAGS='-O0'

S64='$(TOOLSDIR)/set64bitConst.sh'
#EH3 MAKEDEPEND='${TOOLSDIR}/xmakedepend'
#EH3 MAKEDEPEND=makedepend
DEFINES='-DWORDLENGTH=4'
INCLUDES='-I/sw/include'
LIBS='-L/sw/lib'

#  For IEEE, use the "-ffloat-store" option
if test "x$IEEE" = x ; then
    FFLAGS='-Wimplicit -Wunused -Wuninitialized'
    FOPTIM='-O3 -funroll-loops'
else
    FFLAGS='-Wimplicit -Wunused -ffloat-store'
    FOPTIM='-O0'
fi


