#!/bin/bash
#
# $Header: /u/gcmpack/MITgcm/tools/build_options/darwin_ia32_gfortran,v 1.12 2011/09/20 14:44:52 jmc Exp $
# $Name:  $

# Tested on MacBook Pro with Snow Leopard
#- on 20-Nov-2009, without MPI:
#    gcc and gfortran obtained from
# http://hpc.sourceforge.net/
# http://prdownloads.sourceforge.net/hpc/gcc-snwleo-intel-bin.tar.gz?download
# http://prdownloads.sourceforge.net/hpc/gfortran-snwleo-intel-bin.tar.gz?download
#
#- on 23-Dec-2009, with MPI:
#    gfortran (version 4.3.1) obtained via fink
#    OpenMPI (version 1.4) obtained from http://www.open.mpi.org

#-- Note: default location of NetCDF & MPI setting provided in this optfile 
#         are not standard. For this reason, you might need:
#    1) to set NETCDF_ROOT to where the NetCDF is installed, e.g.:
#       export NETCDF_ROOT='/usr/NetCDF'
#    2) for MPI, to set environment variable MPI_INC_DIR to the include
#       directory of your MPI implementation

if test "x$MPI" = xtrue ; then
# CC=mpicc
  FC=mpif90
  LINK=$FC
else
# CC=gcc
  FC=gfortran
  LINK=$FC
fi

#FC_NAMEMANGLE="#define FC_NAMEMANGLE(X) _ ## X ## _"
#FC_NAMEMANGLE="#define FC_NAMEMANGLE(X) X"
#FC_NAMEMANGLE="#define FC_NAMEMANGLE(X) X ## _"
#MAKEDEPEND=tools_xmakedepend
#MAKEDEPEND=cyrus_makedepend

S64='$(TOOLSDIR)/set64bitConst.sh'
DEFINES='-DWORDLENGTH=4 -DNML_TERMINATOR'
CPP='/usr/bin/cpp -traditional -P'
EXTENDED_SRC_FLAG='-ffixed-line-length-132'

#Following flag is needed when using 32-bit gfortran with 64-bit gcc,
#as can be the case right after switching to Snow Leopard.
#CFLAGS='-arch i386'

NOOPTFLAGS='-O0'
NOOPTFILES=''

FFLAGS="$FFLAGS -fsecond-underscore -fconvert=big-endian"
#- might want to use '-fdefault-real-8' for fizhi pkg:
#FFLAGS="$FFLAGS -fdefault-real-8"

if test "x$IEEE" = x ; then     #- with optimisation:
    FFLAGS="$FFLAGS -Wunused -Wuninitialized"
    FOPTIM='-O3 -funroll-loops'
    NOOPTFLAGS='-O2 -funroll-loops'
    NOOPTFILES='gad_c4_adv_x.F gad_u3_adv_x.F'
else                            #- no optimisation + IEEE :
    FFLAGS="$FFLAGS -Wunused -ffloat-store"
    FOPTIM='-O0'
fi

INCLUDEDIRS=''
INCLUDES=''
LIBS=''

if [ "x$NETCDF_ROOT" != x ] ; then
    INCLUDEDIR="${NETCDF_ROOT}/include"
    INCLUDES="-I${NETCDF_ROOT}/include"
    LIBDIR="${NETCDF_ROOT}/lib"
    LIBS="-L${NETCDF_ROOT}/lib"
else
    #-- default NetCDF location: from former darwin_ia32_gfortran optfile:
    INCLUDEDIRS='/sw/include'
    INCLUDES='-I/sw/include'
    LIBS='-L/sw/lib'
fi

if [ -n "$MPI_INC_DIR" -a "x$MPI" = xtrue ] ; then
    INCLUDES="$INCLUDES -I$MPI_INC_DIR"
    INCLUDEDIRS="$INCLUDEDIRS $MPI_INC_DIR"
    MPIINCLUDEDIR="$MPI_INC_DIR"
    MPI_HEADER_FILES='mpif.h mpiof.h'
    MPI_HEADER_FILES_INC='./mpi_headers/mpif.h ./mpi_headers/mpiof.h'
elif [ "x$MPI" = xtrue ] ; then
    #-- default MPI header location: from former darwin_ia32_gfortran+mpi optfile:
    INCLUDES='-I/usr/local/include -I/opt/openmpi/include'
    LIBS='-L/usr/local/lib'
fi
