#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/Attic/hp-ux+mpi,v 1.2 2003/08/27 22:12:31 edhill Exp $
#

S64='$(TOOLSDIR)/set64bitConst.sh'
MAKEDEPEND=makedepend
DEFINES='-DWORDLENGTH=4'


FC='mpif77'
LINK='mpif77'
INCLUDES='-I/opt/mpi/include'
