#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/Attic/irix64+ieee,v 1.2 2003/08/27 22:12:31 edhill Exp $
#

S64='$(TOOLSDIR)/set64bitConst.sh'
MAKEDEPEND=makedepend
DEFINES='-DWORDLENGTH=4'


INCLUDES='-I/usr/local/mpi/include'
FFLAGS='-extend_source -mp -mpio -bytereclen -r10000 -mips4 -r8 -static'
FOPTIM='-O3'
FFLAGS='-extend_source -mp -mpio -bytereclen -r10000 -mips4 -static'
FOPTIM='-O0 -OPT:IEEE_arithmetic=1 -OPT:IEEE_NaN_inf=ON'
RMFILES='rii_files'
