#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/Attic/irix32,v 1.2 2003/08/27 22:12:31 edhill Exp $
#

S64='$(TOOLSDIR)/set64bitConst.sh'
MAKEDEPEND=makedepend
DEFINES='-DWORDLENGTH=4'


INCLUDES='-I/usr/include'
FFLAGS='-extend_source -bytereclen -r10000 -64'
FOPTIM='-O2'
NOOPTFLAGS='-O0'
LIBS='-lmpi'
