#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/irix64_ip30_f77,v 1.1
2004/02/21 14:41:09 dimitri Exp $
#

S64='$(TOOLSDIR)/set64bitConst.sh'
%MAKEDEPEND=makedepend
CPP='/lib/cpp -P -traditional'

DEFINES='-DTARGET_SGI -DWORDLENGTH=4'
FC='f77'
FC_NAMEMANGLE='#define FC_NAMEMANGLE(X) X ## _'
FFLAGS='-n32 -extend_source -bytereclen'
FOPTIM='-O3 -OPT:Olimit=0:roundoff=3:div_split=ON:alias=typed'
LIBS='-lmpi'
INCLUDEDIRS='/usr/include'

