#!/bin/bash
#
# $Header: /u/gcmpack/MITgcm/tools/build_options/Attic/irix64_ip35_f77,v 1.2 2010/03/21 22:22:52 jmc Exp $
# $Name:  $

S64='$(TOOLSDIR)/set64bitConst.sh'
MAKEDEPEND=makedepend
CPP='/lib/cpp -P -traditional'
DEFINES='-DTARGET_SGI -DWORDLENGTH=4'
FC='f77'
FFLAGS='-extend_source -mp -mpio -bytereclen -mips4 -r8 -static'
FOPTIM='-O3'
LIBS='-L/opt/mpt/1510/usr/lib64 -lmpi'
INCLUDEDIRS='/opt/mpt/1510/usr/include'
