#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/Attic/irix64_ip27_f77+mpi_nas_turing,v 1.1 2004/07/24 00:04:15 heimbach Exp $
#
# adapted to turing.nas.nasa.gov
# heimbach@mit.edu

S64='$(TOOLSDIR)/set64bitConst.sh'
MAKEDEPEND=makedepend
CPP='/lib/cpp -P -traditional'

DEFINES='-DTARGET_SGI -DWORDLENGTH=4'
FC='f77'
FFLAGS='-n32 -extend_source -bytereclen'
FOPTIM='-O3 -OPT:Olimit=0:roundoff=3:div_split=ON:alias=typed'
LIBS='-lmpi -lscs'
INCLUDEDIRS='/opt/mpt/mpt/usr/include'
