#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/Attic/irix64_ip27_f77+mpi_nas_turing,v 1.2 2004/07/30 00:33:40 heimbach Exp $
#
# adapted for compilation on turing.nas.nasa.gov
# and execute on turing, lomax, chapman

S64='$(TOOLSDIR)/set64bitConst.sh'
MAKEDEPEND=makedepend
CPP='/lib/cpp -P'
DEFINES='-DTARGET_SGI -DWORDLENGTH=4'
FC='f77'
FFLAGS='-extend_source -mp -mpio -bytereclen -mips4 -r8 -static'
FOPTIM='-O3'
LIBS='-lmpi'
INCLUDEDIRS='/opt/mpt/mpt/usr/include/'
