#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/Attic/irix64_ip35+mpi_gfdl,v 1.2 2004/11/17 04:58:25 heimbach Exp $
#

S64='$(TOOLSDIR)/set64bitConst.sh'
MAKEDEPEND=makedepend
CPP='/lib/cpp -P'
DEFINES='-DTARGET_SGI -DWORDLENGTH=4'
FC='f77'
FFLAGS='-extend_source -mp -mpio -bytereclen -mips4 -r8 -static'
FOPTIM='-O3'
LIBS='-L/opt/mpt/1510/usr/lib64 -lmpi'
INCLUDEDIRS='/opt/mpt/1510/usr/include'
