#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/Attic/linux_g77_faulks,v 1.3 2003/08/29 00:41:37 edhill Exp $
#

S64='$(TOOLSDIR)/set64bitConst.sh'
MAKEDEPEND=makedepend
DEFINES='-D_BYTESWAPIO -DWORDLENGTH=4'


LN='/bin/ln -s'
CPP='/lib/cpp  -traditional -P'
FFLAGS='-Wimplicit -Wunused -Wuninitialized -ffloat-store'
FOPTIM='-O3 -malign-double -funroll-loops'
NOOPTFLAGS='-O0'
FC=g77
LINK=g77


