#!/bin/bash

#  Build options for the intel compiler with OpenAD

FC=ifort
F90C=ifort
F90FIXEDFORMAT='-fixed -Tf' 
DEFINES='-DWORDLENGTH=4'
LINK='ifort -static'
CPP='cpp  -traditional -P'
INCLUDES=''
LIBS=''

if test "x$IEEE" = x ; then
    F90OPTIM='-O3'
    FOPTIM='-O3 -align'
    FFLAGS='-132 -r8 -i4 -w95 -W0 -WB -convert big_endian -assume byterecl'
else
    F90OPTIM='-O0 -g'
    FOPTIM='-O0 -g -noalign'
    FFLAGS='-132 -r8 -i4 -w95 -W0 -WB -xN -pc64 -convert big_endian -assume byterecl'
fi

F90FLAGS=$FFLAGS
