#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/linux_ia32_lf95,v 1.1 2003/12/04 22:42:29 edhill Exp $
#

DEFINES='-DWORDLENGTH=4'
CPP='/lib/cpp -traditional -P'
FC='lf95'
# FFLAGS='-byteswapio -r8 -Mnodclchk -Mextend'
# FOPTIM='-tp p6 -v -O2 -Munroll -Mvect=cachesize:512000,transform -Kieee'

