#!/bin/bash
#
#  optifile for fimm.bccs.uib.no
#  http://www.parallab.uib.no/resources/cluster/nodemem
#
#  uses mpif90 wrapper for ifort
#  issues:
#  * -save option needed for GISS atmosphere
#  * cannot use ifort options -assume, -convert
#  * needs low optimization leve

FC=mpif90
F90C=mpif90
DEFINES='-DWORDLENGTH=1 -D_BYTESWAPIO'
LINK='mpif90'
CPP='/lib/cpp  -traditional -P'
FFLAGS='-132 -r8 -i4 -save -g -traceback'
F90FLAGS='-132 -r8 -i4 -save -g -traceback'
FOPTIM=''
LIBS='-L/opt/mpich/intel/lib'
INCLUDES='$INCLUDES -I/opt/mpich/intel/include'
INCLUDEDIRS='/opt/mpich/intel/include'

