#!/bin/bash
#
# $Header: /u/gcmpack/MITgcm/tools/build_options/linux_ia64_ifort_altix_jpl,v 1.2 2010/03/21 17:58:17 jmc Exp $
# $Name:  $

#  tested on pollux.jpl.nasa.gov

FC=ifort

DEFINES='-DWORDLENGTH=4'
CPP='/lib/cpp  -traditional -P'
EXTENDED_SRC_FLAG='-132'

INCLUDEDIRS="/usr/include"
INCLUDES="-I/usr/include"

NOOPTFILES='ini_curvilinear_grid.F'
NOOPTFLAGS='-O3'

FFLAGS="$FFLAGS -mp -w95 -W0 -WB -convert big_endian -assume byterecl"
FOPTIM='-O3 -align -ip'
#- might want to use '-r8' for fizhi pkg:
#FFLAGS="$FFLAGS -r8"

