#!/bin/bash
#
#  Ed Hill
#
#  tested on orion.jpl.nasa.gov (Linux orion 2.4.21-sgi230r7 #1 SMP Tue Oct 7 22:38:53 PDT 2003 ia64 unknown), 20031029


CPP='/lib/cpp  -traditional -P'

#  Note that the -mp switch is for ieee "maintain precision" and is
#  roughly equivalent to -ieee
if test "x$IEEE" = x ; then
    FFLAGS='-mp -132 -r8 -i4 -w95 -W0 -WB -save'
else
    FFLAGS='-mp -132 -r8 -i4 -w95 -W0 -WB -save'
fi

FOPTIM='-O3 -align'
#P3  FOPTIM     = ( $FOPTIM '-tpp6 -xWKM' ) 
#P4  FOPTIM     = ( $FOPTIM '-tpp7 -xWKM' ) 
INCLUDES='-I/u/edhill/pkg/netcdf-3.6.0/ifort/include'
LIBS='-L/u/edhill/pkg/netcdf-3.6.0/ifort/lib -lnetcdf'

FC=ifort
DEFINES='-D_BYTESWAPIO -DWORDLENGTH=1'



