#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/Attic/linux_ifc+ieee,v 1.2 2003/08/27 22:12:31 edhill Exp $
#

S64='$(TOOLSDIR)/set64bitConst.sh'
MAKEDEPEND=makedepend
DEFINES='-DWORDLENGTH=4'


LN='/bin/ln -s'
CPP='/lib/cpp  -traditional -P'
FFLAGS='-132 -r8 -i4 -w95 -W0 -WB'
FOPTIM='-O3 -align'
#P3  FOPTIM     = ( $FOPTIM '-tpp6 -xWKM' ) 
#P4  FOPTIM     = ( $FOPTIM '-tpp7 -xWKM' ) 
LIBS='-lPEPCF90'
