#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/Attic/linux_ia32_g77+mpi_itrda,v 1.8 2004/11/16 18:59:30 edhill Exp $
#  $Name:  $
#
# adapted to itrda.acesgrid.org

DEFINES='-DALLOW_USE_MPI -DALWAYS_USE_MPI -D_BYTESWAPIO -DWORDLENGTH=4'
CPP='cpp  -traditional -P'

FC='mpif77'
CC='mpicc'
LINK='mpif77'
LIBS='-L/usr/local/pkg/mpich/mpich-gcc/lib '
INCLUDES='-I/usr/local/pkg/mpich/mpich-gcc/include '

if test "x$IEEE" = x ; then
    #  No need for IEEE-754
    FFLAGS='-Wimplicit -Wunused -Wuninitialized'
    FOPTIM='-O3 -malign-double -funroll-loops'
else
    #  Try to follow IEEE-754
    FFLAGS='-Wimplicit -Wunused -ffloat-store'
    FOPTIM='-O0 -malign-double'
fi
NOOPTFLAGS='-O0'

