#!/bin/bash
#
#  Ed Hill
#
#  tested on orion.jpl.nasa.gov (Linux orion 2.4.21-sgi230r7 #1 SMP Tue Oct 7 22:38:53 PDT 2003 ia64 unknown), 20031029


CPP='/lib/cpp  -traditional -P'

#  Note that the -mp switch is for ieee "maintain precision" and is
#  roughly equivalent to -ieee
if test "x$IEEE" = x ; then
    FFLAGS='-mp -132 -r8 -i4 -w95 -W0 -WB'
else
    FFLAGS='-mp -132 -r8 -i4 -w95 -W0 -WB'
fi

FOPTIM='-O3 -align'
#P3  FOPTIM     = ( $FOPTIM '-tpp6 -xWKM' ) 
#P4  FOPTIM     = ( $FOPTIM '-tpp7 -xWKM' ) 
LIBS='-L/opt/sgi/mpt/1.9.1.0/lib -lPEPCF90 -lmpi'

FC=efc
DEFINES='-DALLOW_USE_MPI -DALWAYS_USE_MPI -D_BYTESWAPIO -DWORDLENGTH=4'

INCLUDES='-I/opt/sgi/mpt/1.9.1.0/include'
INCLUDEDIRS='/opt/sgi/mpt/1.9.1.0/include'
