#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/Attic/linux_ia32_ifort+mpi_beagle,v 1.2 2008/07/23 19:01:28 jahn Exp $
#
#  These are the build options used with the Intel 9.x compiler for
#  testing on Beagle.
#
#  Please note that the appropriate module commands:
#
#    module add intel/9.1.051
#    module add mpich-mx/1.2.7..1/intel/9.1.051
#
#  will add /home/ibm/util/mpich-mx-1.2.7..1/icc/9.1.051/lib,
#  /opt/intel/cce/9.1.051/lib and /opt/intel/fce/9.1.051/lib
#  to LD_LIBRARY_PATH which is needed by any executables generated
#  with this optfile.
#  The SGE -V option for exporting environment variables may also be
#  helpful if you encounter missing-library problems.  Or,
#  alternatively, one may choose to link with one of the intel
#  "-static" or "-i-static" flags.


mpichhome=/home/ibm/util/mpich-mx-1.2.7..1/icc/9.1.051
#netcdfhome=/home/software/netcdf/netcdf-3.6.2/intel-9.1.051
netcdfhome=/home/ibm/util/netcdf-3.6.2


FC='mpif77'
CC='mpicc'
F90C='mpif90 -fixed -c '
LINK='mpif77'
INCLUDES="-I$mpichhome/include -I$netcdfhome/include"
LIBS="-L$mpichhome/lib -L$netcdfhome/lib"


# -DIFORT turns on ifort-specific declarations in darwin (RAND is not an intrinsic)
DEFINES='-DALLOW_USE_MPI -DALWAYS_USE_MPI -DWORDLENGTH=4 -DIFORT'
CPP='cpp  -traditional -P'

NOOPTFLAGS='-O0'
NOOPTFILES='mds_byteswapr8.F mds_byteswapr4.F mds_byteswapi4.F'

#  Note that the -mp switch is for ieee "maintain precision" and is
#  roughly equivalent to -ieee
if test "x$IEEE" = x ; then
    FOPTIM='-O3 -align'
    #P3 FOPTIM=$FOPTIM' -tpp6 -xWKM'
    #P4 FOPTIM=$FOPTIM' -tpp7 -xWKM'
    # FFLAGS='-132 -r8 -i4 -w95 -W0 -WB -assume byterecl -convert big_endian'
    FFLAGS='-132 -r8 -i4 -w95 -W0 -WB -xT -fno-alias -assume byterecl -convert big_endian' 
    # FFLAGS='-132 -O3 -xT -fPIC -ipo -fno-alias'
else
    # FOPTIM='-O0 -noalign -CA -CB -CU -CV -CS'
    FOPTIM='-O0 -noalign'
    # FFLAGS='-mp -132 -r8 -i4 -w95 -W0 -WB'
    # FFLAGS='-132 -r8 -i4 -w95 -W0 -WB -pc64 -xW -assume byterecl -convert big_endian'
    FFLAGS='-132 -r8 -i4 -w95 -W0 -WB -pc64 -xT -fno-alias -assume byterecl -convert big_endian' 
    # FFLAGS='-132 -O3 -xT -fPIC -ipo -fno-alias'
    # FLAGS='-mp -132 -r8 -i4 -w95 -W0 -WB -assume byterecl -convert big_endian'
fi
F90FLAGS=$FFLAGS
F90OPTIM=$FOPTIM

NOOPTFILES=$NOOPTFILES' mitcplr_char2real.F mitcplr_real2char.F'
NOOPTFILES=$NOOPTFILES' mitcplr_char2int.F mitcplr_int2char.F mds_byteswap.F'
