#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/Attic/linux_ia32_g77+mpi_itrda,v 1.4 2004/08/29 15:38:33 edhill Exp $
#  $Name:  $
#


FC='/usr/local/mpich/mpich-1.2.1..7b_gnu/bin/mpif77'
CC='/usr/local/mpich/mpich-1.2.1..7b_gnu/bin/mpicc'
DEFINES='-DALLOW_USE_MPI -DALWAYS_USE_MPI -D_BYTESWAPIO -DWORDLENGTH=4'
INCLUDEDIRS='-I/usr/local/mpich/mpich-1.2.1..7b_gnu/include/'
CPP='/lib/cpp  -traditional -P'
LINK='/usr/local/mpich/mpich-1.2.1..7b_gnu/bin/mpif77'
LIBS='-L/usr/local/mpich/mpich-1.2.1..7b_gnu/lib/ -lfmpich -lmpich'
NOOPTFLAGS='-O0'


if test "x$IEEE" = x ; then
    #  No need for IEEE-754
    FFLAGS='-Wimplicit -Wunused -Wuninitialized'
    FOPTIM='-O3 -malign-double -funroll-loops'
else
    #  Try to follow IEEE-754
    FFLAGS='-Wimplicit -Wunused -ffloat-store'
    FOPTIM='-O0 -malign-double'
fi

# netcdf
# LIBS="-lnetcdf"

