#!/bin/bash
#
#  Build options for the intel compiler with OpenAD

FC=ifort
F90C=ifort
F90FIXEDFORMAT='-fixed -Tf' 
DEFINES='-DWORDLENGTH=4'
LINK='ifort -static'
CPP='cpp  -traditional -P'
INCLUDES=''
LIBS=''

if test "x$IEEE" = x ; then
    FOPTIM='-O2 -align'
    FFLAGS='-132 -r8 -i4 -w95 -W0 -WB -convert big_endian -assume byterecl -m64 -fPIC'
else
    FOPTIM='-O0 -g -noalign -mp'
    FFLAGS='-132 -r8 -i4 -w95 -W0 -WB -convert big_endian -assume byterecl -m64 -fPIC'
fi

F90OPTIM=$FOPTIM
F90FLAGS=$FFLAGS
