#!/bin/bash
#
#  Ed Hill
#
#  tested on orion.jpl.nasa.gov (Linux orion 2.4.21-sgi230r7 #1 SMP Tue Oct 7 22:38:53 PDT 2003 ia64 unknown), 20031029
#
# adapted to meinesz.mit.edu (eaps6)
# heimbach@mit.edu

CPP='/lib/cpp  -traditional -P'

# the '-convert big_endian' is crucial on this platform
# -D_BYTESWAPIO doesn't work
# also switch to -DWORDLENGTH=1
#
DEFINES='-DALLOW_USE_MPI -DALWAYS_USE_MPI -DWORDLENGTH=1'

# These paths will likely change to newer versions of ifort
#
LIBS='-L/opt/intel_fc_80/lib -lmpi'
FC=/opt/intel_fc_80/bin/ifort
FFLAGS='-extend_source -O2 -tpp2 -ftz -fno-alias -fno-fnalias -convert big_endian'

# FOPTIM='-O3 -align'
#
#P3  FOPTIM     = ( $FOPTIM '-tpp6 -xWKM' ) 
#P4  FOPTIM     = ( $FOPTIM '-tpp7 -xWKM' )

