#!/bin/bash
#
#  Ed Hill
#
#  tested on orion.jpl.nasa.gov (Linux orion 2.4.21-sgi230r7 #1 SMP Tue Oct 7 22:38:53 PDT 2003 ia64 unknown), 20031029
#
# adapted to GFDL's Itanium cluster
#  heimbach@mit.edu and baylor@mit.edu
# 
#  Will need to do module_load ifort.9.1.039 mpt-1.14 first

CPP='/lib/cpp  -traditional -P'

# the '-convert big_endian' is crucial on this platform
# -D_BYTESWAPIO doesn't work
    FFLAGS='-mp -132 -r8 -i4 -w95 -W0 -WB -convert big_endian'

FOPTIM='-O3 -align -ip'
NOOPTFILES='ini_curvilinear_grid.F'
NOOPTFLAGS='-O3'

#P3  FOPTIM     = ( $FOPTIM '-tpp6 -xWKM' ) 
#P4  FOPTIM     = ( $FOPTIM '-tpp7 -xWKM' ) 
LIBS='-lmpi -lnetcdf'

FC=ifort
# Using gcc instead of icc since this is how netcdf was compiled
#CC=icc
DEFINES='-DALLOW_USE_MPI -DALWAYS_USE_MPI -DWORDLENGTH=4'

#SKIP_NETCDF_CHECK=t
#HAVE_NETCDF=t

# These paths will likely change to newer versions of ifort
INCLUDES="-I/usr/local/include  -I$CPATH"
INCLUDEDIRS="/usr/local/include $CPATH"
#LIBDIRS='/usr/local/lib'
#MPIINCLUDEDIR='/opt/mpt/1.14/include'
#MPI_HEADER_FILES='mpif.h mpiof.h mpif_parameters.h'
#MPI_HEADER_FILES_INC='./mpi_headers/mpif.h ./mpi_headers/mpiof.h ./mpi_headers/mpif_parameters.h'
