#!/bin/bash
#
#  tested on pollux.jpl.nasa.gov

FC=ifort

DEFINES='-DWORDLENGTH=4'
CPP='/lib/cpp  -traditional -P'
EXTENDED_SRC_FLAG='-132'

NOOPTFILES='ini_curvilinear_grid.F'
NOOPTFLAGS='-O3'

FFLAGS="$FFLAGS -mp -w95 -W0 -WB -convert big_endian -assume byterecl"
FOPTIM='-O3 -align -ip'
#- might want to use '-r8' for fizhi pkg:
#FFLAGS="$FFLAGS -r8"

INCLUDEDIRS="/usr/include"
INCLUDES="-I/usr/include"
if test "x$MPI" = xtrue ; then
  LIBS='-lmpi'
fi


