#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/linux_alpha_g77,v 1.2 2003/11/13 22:03:39 edhill Exp $
#

FC='g77'
FFLAGS=' '
FOPTIM='-ffast-math -fexpensive-optimizations -fomit-frame-pointer -O3'
DEFINES='-DWORDLENGTH=4'
CPP='cpp  -traditional -P'

