#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/linux_amd64_pgf77+mpi_ncar,v 1.2 2010/03/21 21:34:01 jmc Exp $
#  $Name:  $
#
# Build options for Suse SLES-8.1 Opteron
# tested on (Linux ln0127en 2.4.21-143-numa #1 SMP Fri Oct 31 00:17:52 UTC 2003 x86_64 unknown) system 20041512
#

FC=mpif77
CC=mpicc
LINK=mpif77

DEFINES='-DWORDLENGTH=4 -DALLOW_USE_MPI -DALWAYS_USE_MPI'
CPP='cpp  -traditional -P'
EXTENDED_SRC_FLAG='-Mextend'

MAKEDEPEND=/usr/X11R6/bin/makedepend
INCLUDES=-I/opt/mpich-gm/include

NOOPTFLAGS='-O0'

if test "x$IEEE" = x ; then
    #  No need for IEEE-754
    FFLAGS="$FFLAGS -byteswapio -Mnodclchk -Ktrap=fp"
    FOPTIM='-tp k8-64 -pc=64 -fastsse -O3 -Msmart -Mvect=cachesize:1048576,transform'
else
    #  Try to follow IEEE-754
    FFLAGS="$FFLAGS -byteswapio -Ktrap=fp"
    FOPTIM='-tp k8-64 -pc=64 -fastsse -O3 -Msmart -Kieee -Mvect=cachesize:1048576,transform'
fi
#- might want to use '-r8' for fizhi pkg:
#FFLAGS="$FFLAGS -r8"

