#!/bin/bash
#
#  Ed Hill
#
#  tested on faulks, 20030818
#
#  Build options for the intel 8.0 fortran compiler
#  the compiler is now called ifort (not ifc) and it appears to
#  need -DWORDLENGTH=1 and not -DWORDLENGTH=4 (which is what ifc 6.0) used to have.
#  ph: use ifort compiler options -convert big_endian -assume byterecl

FC=ifort
F90C=ifort
F90FIXEDFORMAT='-fixed -Tf' 
DEFINES='-DWORDLENGTH=4'
LINK='ifort -static'
CPP='cpp  -traditional -P'
INCLUDES='-I/usr/include/netcdf'

#  Note that the -mp switch is for ieee "maintain precision" and is
#  roughly equivalent to -ieee
if test "x$IEEE" = x ; then
    FOPTIM='-O3 -align'
#P3 FOPTIM=$FOPTIM' -tpp6 -xWKM'
#P4 FOPTIM=$FOPTIM' -tpp7 -xWKM'
    FFLAGS='-132 -r8 -i4 -w95 -W0 -WB -convert big_endian -assume byterecl'
    F90FLAGS='-r8 -i4 -w95 -W0 -WB -convert big_endian -assume byterecl'
else
    FOPTIM='-O0 -noalign'
    FFLAGS='-132 -r8 -i4 -w95 -W0 -WB -xN -pc64 -convert big_endian -assume byterecl'
   #FFLAGS='-mp -132 -r8 -i4 -w95 -W0 -WB'
fi



