#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/Attic/linux_ia32_ifc+mpi_itrda,v 1.5 2005/08/23 22:08:49 jmc Exp $
#
# adapted to itrda.acesgrid.org
# Note:
# currently need to ad to your .cshrc, .bashrc, etc. 
# setenv LD_LIBRARY_PATH /usr/local/pkg/ifc/ifc-8.0.034/lib
# is required

FC='mpif77'
CC='mpicc'
LINK='mpif77'
INCLUDES='-I/usr/local/pkg/ifc/ifc-8.1.018/include -I/usr/local/pkg/mpich/mpich-intel/include/'
LIBS='-L/usr/local/pkg/ifc/ifc-8.1.018/lib'

DEFINES='-DALLOW_USE_MPI -DALWAYS_USE_MPI -D_BYTESWAPIO -DWORDLENGTH=1'
CPP='cpp  -traditional -P'

NOOPTFLAGS='-O0'
NOOPTFILES='mds_byteswapr8.F mds_byteswapr4.F mds_byteswapi4.F'

#  Note that the -mp switch is for ieee "maintain precision" and is
#  roughly equivalent to -ieee
if test "x$IEEE" = x ; then
    FOPTIM='-O3 -align'
    FFLAGS='-132 -r8 -i4 -w95 -W0 -WB'
else
   #FOPTIM='-O0 -noalign -CA -CB -CU -CV -CS'
    FOPTIM='-O0 -noalign'
   #FFLAGS='-mp -132 -r8 -i4 -w95 -W0 -WB'
    FFLAGS='-132 -r8 -i4 -w95 -W0 -WB -pc64 -xW'
fi

NOOPTFILES=$NOOPTFILES' mitcplr_char2real.F mitcplr_real2char.F'
NOOPTFILES=$NOOPTFILES' mitcplr_char2int.F mitcplr_int2char.F mds_byteswap.F'
