#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/Attic/linux_pgf77,v 1.3 2003/09/02 00:02:04 edhill Exp $
#

S64='$(TOOLSDIR)/set64bitConst.sh'
MAKEDEPEND=makedepend
DEFINES='-DWORDLENGTH=4'


LN='/bin/ln -s'
CPP='/lib/cpp  -traditional -P'
FC='pgf77'
LINK='pgf77'
FFLAGS='-byteswapio -r8 -Mnodclchk -Mextend'
FOPTIM='-tp p6 -v -O2 -Munroll -Mvect=cachesize:512000,transform -Kieee'
