#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/Attic/linux_ia32_ifc+mpi_cg01,v 1.2 2003/11/13 22:03:39 edhill Exp $
#

DEFINES='-DALLOW_USE_MPI -DALWAYS_USE_MPI -D_BYTESWAPIO -DWORDLENGTH=4'
CPP='/lib/cpp  -traditional -P'

#  Note that the -mp switch is for ieee "maintain precision" and is
#  roughly equivalent to -ieee
if test "x$IEEE" = x ; then
    FOPTIM='-O3 -align'
    FFLAGS='-132 -r8 -i4 -w95 -W0 -WB'
else
    FFLAGS='-mp -132 -r8 -i4 -w95 -W0 -WB'
fi

LIBS='-lPEPCF90'
NOOPTFLAGS='-O0'
FC='/usr/local/pkg/mpi/mpi-1.2.4..8a-gm-1.5/intel/bin/mpif77'
LINK='/usr/local/pkg/mpi/mpi-1.2.4..8a-gm-1.5/intel/bin/mpif77'
INCLUDEDIRS='/usr/local/pkg/mpi/mpi-1.2.4..8a-gm-1.5/intel/include'

