#!/bin/bash
#
#  tested on pollux.jpl.nasa.gov

CPP='/lib/cpp  -traditional -P'
FFLAGS='-mp -132 -r8 -i4 -w95 -W0 -WB -convert big_endian -assume byterecl'
FOPTIM='-O3 -align -ip'
NOOPTFILES='ini_curvilinear_grid.F'
NOOPTFLAGS='-O3'
LIBS='-lmpi'
FC=ifort
DEFINES='-DALLOW_USE_MPI -DALWAYS_USE_MPI -DWORDLENGTH=4'
INCLUDES="-I/usr/include"
INCLUDEDIRS="/usr/include"
