#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/linux_ia32_pgf77,v 1.3 2004/07/30 19:25:03 molod Exp $
#

DEFINES='-DWORDLENGTH=4'
CPP='/lib/cpp -traditional -P'
FC='pgf77'
CC='gcc'
FFLAGS='-byteswapio -r8 -Mnodclchk -Mextend'
FOPTIM='-tp p6 -v -O2 -Munroll -Mvect=cachesize:512000,transform -Kieee'

