#!/bin/bash
#
# $Header: /u/gcmpack/MITgcm/tools/build_options/Attic/linux_alpha_g77+mpi,v 1.3 2010/03/21 22:22:52 jmc Exp $
# $Name:  $

FC='g77'
FOPTIM='-ffast-math -fexpensive-optimizations -fomit-frame-pointer -O3'
DEFINES='-DWORDLENGTH=4'
LIBS='-L/usr/local/lib/LINUX/ch_p4/ -lfmpich -lmpich'
INCLUDES='-I/usr/local/include'
CPP='cpp  -traditional -P'


#  For IEEE, use the "-ffloat-store" option
if test "x$IEEE" = x ; then
    FFLAGS='-Wimplicit -Wunused -Wuninitialized'
    FOPTIM='-O3 -funroll-loops'
else
    FFLAGS='-Wimplicit -Wunused -ffloat-store'
    FOPTIM='-O0'
fi

