#!/bin/bash
#
#  Ed Hill
#
#  tested on faulks, 20030818
#
#  Build options for the intel 8.0 fortran compiler
#  the compiler is now called ifort (not ifc) and it appears to
#  need -DWORDLENGTH=1 and not -DWORDLENGTH=4 (which is what ifc 6.0) used to have.


FC=mpif77
CC=mpicc
DEFINES='-DWORDLENGTH=4'
LINK=mpif77
CPP='cpp  -traditional -P'
INCLUDES='-I/usr/local/pkg/mpich/mpich-intel/include -I/usr/local/pkg/ifc/ifc-8.1.018/include'

#  Note that the -mp switch is for ieee "maintain precision" and is
#  roughly equivalent to -ieee
if test "x$IEEE" = x ; then
    FOPTIM='-O3 -align'
#P3 FOPTIM=$FOPTIM' -tpp6 -xWKM'
#P4 FOPTIM=$FOPTIM' -tpp7 -xWKM'
    FFLAGS='-132 -r8 -i4 -w95 -W0 -WB -assume byterecl -convert big_endian'
else
    FFLAGS='-mp -132 -r8 -i4 -w95 -W0 -WB -assume byterecl -convert big_endian'
fi



