#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/Attic/linux_g77,v 1.2 2003/08/27 22:12:31 edhill Exp $
#

S64='$(TOOLSDIR)/set64bitConst.sh'
MAKEDEPEND=makedepend


LN='/bin/ln -s'
CPP='/lib/cpp  -traditional -P'
FFLAGS='-Wimplicit -Wunused -Wuninitialized -ffloat-store'
FOPTIM='-O3 -malign-double -funroll-loops'
NOOPTFLAGS='-O0'
FC=g77
LINK=g77
DEFINES='-D_BYTESWAPIO -DWORDLENGTH=4'


