#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/linux_amd64_pgf77_ocl,v 1.1 2004/12/22 08:29:10 mlosch Exp $
#
# tested on ocl00.awi-bremerhaven.de
# Linux ocl00 2.4.21-261-smp #1 SMP Wed Nov 17 22:05:59 UTC 2004 x86_64 unknown
# pgf77 5.2-4
# Copyright 1989-2000, The Portland Group, Inc.  All Rights Reserved.
# Copyright 2000-2004, STMicroelectronics, Inc.  All Rights Reserved.

FC='pgf77'
CC='pgcc'
LINK='pgf77'
CPP='/usr/bin/cpp -P -traditional'

DEFINES='-DWORDLENGTH=4'
INCLUDES='-I/var/tmp.shared/netcdf-64/include'
LIBS='-L/var/tmp.shared/netcdf-64/lib -lnetcdf'

if test "x$IEEE" = x ; then
    #  No need for IEEE-754
    FFLAGS='-byteswapio -r8 -Mnodclchk -Mextend'
    FOPTIM='-tp amd64 -O2 -Munroll'
# -Mvect=cachesize:512000,transform
else
    #  Try to follow IEEE-754
    FFLAGS='-byteswapio -r8 -Mnodclchk -Mextend'
    FOPTIM='-tp amd64 -O0 -Munroll -Kieee'
# -Mvect=cachesize:512000,transform
fi
