#!/bin/bash
#
# $Header: /u/gcmpack/MITgcm/tools/build_options/linux_ia64_pgf77+mpi_cray_xt3_jaguar,v 1.2 2010/03/21 21:34:01 jmc Exp $
# $Name:  $

# heimbach@mit.edu, ce107@mit.edu
# tested on jaguarcnl.ccs.ornl.gov CRAY XT3

FC='ftn'
CC='cc'

DEFINES='-DWORDLENGTH=4 -DALLOW_USE_MPI -DALWAYS_USE_MPI -DTARGET_CRAYXT'
CPP='cpp -traditional -P'
EXTENDED_SRC_FLAG='-Mextend'

###INCLUDES='-I/usr/local/mpich-1.2.1/pgi_fortran_binding/include'
INCLUDES="-I${MPICH_DIR_FTN_DEFAULT64}/include"
LIBS='-lfmpich -lmpich'

FFLAGS="$FFLAGS -byteswapio -Mnodclchk"
FOPTIM='-tp k8-64 -pc=64 -fastsse -O3 -Msmart'
# -Mvect=cachesize:512000,transform
#- might want to use '-r8' for fizhi pkg:
#FFLAGS="$FFLAGS -r8"

