#!/bin/bash
#
# $Header: /u/gcmpack/MITgcm/tools/build_options/linux_ia32_pgf77+mpi_aer,v 1.6 2010/12/19 22:42:23 jmc Exp $
# $Name:  $

FC='/opt/mpich/bin/mpif77'
CC='/opt/mpich/bin/mpicc'
LINK='/opt/mpich/bin/mpif77'

DEFINES='-DWORDLENGTH=4 -DNML_EXTENDED_F77'
CPP='cpp  -traditional -P'
EXTENDED_SRC_FLAG='-Mextend'
GET_FC_VERSION="-V"

INCLUDES='-I/opt/mpich/include'
LIBS='-L/opt/mpich/lib/ -lfmpich -lmpich'

if test "x$IEEE" = x ; then
    #  No need for IEEE-754
    FFLAGS="$FFLAGS -byteswapio -Mnodclchk"
    FOPTIM='-fastsse -Mvect=cachesize:524288,transform'
else
    #  Try to follow IEEE-754
    FFLAGS="$FFLAGS -byteswapio"
    FOPTIM='-O0 -Mvect=sse -Mscalarsse -Mcache_align -Mnoflushz -Kieee'
fi
#- might want to use '-r8' for fizhi pkg:
#FFLAGS="$FFLAGS -r8"
