#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/Attic/linux_alpha_g77+mpi,v 1.1 2003/09/29 16:15:24 edhill Exp $
#

FC='g77'
FOPTIM='-ffast-math -fexpensive-optimizations -fomit-frame-pointer -O3'
DEFINES='-DWORDLENGTH=4'
LIBS='-L/usr/local/lib/LINUX/ch_p4/ -lfmpich -lmpich'
INCLUDES='-I/usr/local/include'
CPP='cpp  -traditional -P'
