#!/bin/bash
#
# $Header: /u/gcmpack/MITgcm/tools/build_options/Attic/linux_ia32_ifort+authors_v9,v 1.3 2006/08/31 13:51:19 jmc Exp $
# $Name:  $
#
#  tested on hugo (FC.4), eddy (FC.5): 20060119
#
#  Build options for the intel 9.0 fortran compiler
#  the compiler is now called ifort (not ifc) and it appears to
#  need -DWORDLENGTH=1 and not -DWORDLENGTH=4 (which is what ifc 6.0) used to have.
#  ph: use ifort compiler options -convert big_endian -assume byterecl

FC=/usr/local/pkg/intel/intel_fc_90/bin/ifort
F90C=/usr/local/pkg/intel/intel_fc_90/bin/ifort
F90FIXEDFORMAT='-fixed -Tf' 
DEFINES='-DWORDLENGTH=4'
LINK='/usr/local/pkg/intel/intel_fc_90/bin/ifort -i-static -no-ipo'
CPP='cpp  -traditional -P'
INCLUDES='-I/usr/local/pkg/netcdf/netcdf-3.5.1/include'

#  Note that the -mp switch is for ieee "maintain precision" and is
#  roughly equivalent to -ieee
if test "x$IEEE" = x ; then
    FOPTIM='-O3 -align'
#P3 FOPTIM=$FOPTIM' -tpp6 -xWKM'
#P4 FOPTIM=$FOPTIM' -tpp7 -xWKM'
    FFLAGS='-132 -r8 -i4 -w95 -W0 -WB -convert big_endian -assume byterecl'
    F90FLAGS='-r8 -i4 -w95 -W0 -WB -convert big_endian -assume byterecl'
else
    FOPTIM='-O0 -noalign -check all'
    FFLAGS='-132 -r8 -i4 -w95 -W0 -WB -xN -pc64 -convert big_endian -assume byterecl'
   #FFLAGS='-mp -132 -r8 -i4 -w95 -W0 -WB'
fi

