#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/Attic/linux_ia32_pgf77+mpi,v 1.1 2003/09/29 16:15:24 edhill Exp $
#

DEFINES='-DWORDLENGTH=4'
LN='/bin/ln -s'
FC='pgf77'
INCLUDES='-I/usr/local/mpich-1.2.1/pgi_fortran_binding/include'
LIBS='-L/usr/local/mpich-1.2.1/pgi_fortran_binding/lib/ -lfmpich -lmpich'
INCLUDES='-I/usr/local/include'
LIBS='-L/usr/local/lib/LINUX/ch_p4/ -lfmpich -lmpich'
