#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/linux_amd64_pgf77+mpi_xd1,v 1.9 2010/12/19 22:42:23 jmc Exp $
#  $Name:  $
#
# tested on xd1.awi-bremerhaven.de
# Linux xd1-420-6 2.4.21_H_01_01 #6 SMP Wed Nov 3 15:30:06 PST 2004 x86_64 unknownx
# pgf77 5.2-4
# Copyright 1989-2000, The Portland Group, Inc.  All Rights Reserved.
# Copyright 2000-2004, STMicroelectronics, Inc.  All Rights Reserved.

#FC_NAMEMANGLE="#define FC_NAMEMANGLE(X) X ## _"

FC='mpif77'
CC='mpicc'
LINK='mpif77'

MPI='true'

DEFINES='-DWORDLENGTH=4 -DNML_EXTENDED_F77'
CPP='/usr/bin/cpp -P -traditional'
EXTENDED_SRC_FLAG='-Mextend'
GET_FC_VERSION="-V"

INCLUDES='-I/usr/mpich/mpich-1.2.6-pgi524/include -I/opt/awi/netcdf-3.6.0-p1/include'
LIBS='-L/usr/mpich/mpich-1.2.6-pgi524/lib -Mmpi -L/opt/awi/netcdf-3.6.0-p1/lib -lnetcdf'

if test "x$IEEE" = x ; then
    #  No need for IEEE-754
    FFLAGS="$FFLAGS -byteswapio -Mnodclchk"
    FOPTIM='-O2 -Munroll'
else
    #  Try to follow IEEE-754
    FFLAGS="$FFLAGS -byteswapio"
    FOPTIM='-tp amd64 -O0 -Munroll -Kieee'
fi
#FFLAGS=$FFLAGS' -mcmodel=medium'
#- might want to use '-r8' for fizhi pkg:
#FFLAGS="$FFLAGS -r8"
