#!/bin/bash
#

FC=f77
F90C=f90
CC=cc
LINK=${F90C}
FC_NAMEMANGLE="#define FC_NAMEMANGLE(X) X ## _"
DEFINES='-DWORDLENGTH=4 -DUSE_OMP_THREADING'
CPP='cpp  -traditional -P'
NOOPTFLAGS='-O0 -g -m32 -xfilebyteorder=big16:%all -u -r8const -xopenmp=noopt'
NOOPTFILES=''
EXTENDED_SRC_FLAG='-e'

if test "x$DEVEL" != x ; then
    FFLAGS='-xfilebyteorder=big16:%all -u -r8const -g -xs -C -xcommonchk -xcheck=init_local -fpover -xopenmp=noopt'
else
    FFLAGS='-xfilebyteorder=big16:%all -u -r8const -xopenmp'
fi

if test "x$IEEE" = x ; then
    #  No need for IEEE-754
    FOPTIM='-fast -m32 -xvector=simd -xpad=local'
    LIBS="$LIBS -lmopt"
else
    #  Try to follow IEEE-754
#    FOPTIM='-O0 -m32'
    FOPTIM='-fast -m32 -xpad=local -fsimple=1'
fi
F90FLAGS=$FFLAGS
F90OPTIM=$FOPTIM
CFLAGS='-O3 -m32 -xopenmp'

if [ "x$NETCDF_ROOT" != x ] ; then
    INCLUDEDIR="${NETCDF_ROOT}/include"
    INCLUDES="-I${NETCDF_ROOT}/include"
    LIBDIR="${NETCDF_ROOT}/lib"
    LIBS="-L${NETCDF_ROOT}/lib"
elif [ "x$NETCDF_HOME" != x ]; then
    INCLUDEDIR="${NETCDF_HOME}/include"
    INCLUDES="-I${NETCDF_HOME}/include"
    LIBDIR="${NETCDF_HOME}/lib"
    LIBS="-L${NETCDF_HOME}/lib"
elif [ "x$NETCDF_INC" != x -a "x$NETCDF_LIB" != x ]; then
    NETCDF_INC=`echo $NETCDF_INC | sed 's/-I//g'`
    NETCDF_LIB=`echo $NETCDF_LIB | sed 's/-L//g'`
    INCLUDEDIR="${NETCDF_INC}"
    INCLUDES="-I${NETCDF_INC}"
    LIBDIR="${NETCDF_LIB}"
    LIBS="-L${NETCDF_LIB}"
elif [ "x$NETCDF_INCDIR" != x -a "x$NETCDF_LIBDIR" != x ]; then
    INCLUDEDIR="${NETCDF_INCDIR}"
    INCLUDES="-I${NETCDF_INCDIR}"
    LIBDIR="${NETCDF_LIBDIR}"
    LIBS="-L${NETCDF_LIBDIR}"
elif test -d /usr/include/netcdf-3 ; then
    INCLUDES='-I/usr/include/netcdf-3'
    LIBS='-L/usr/lib/netcdf-3'
elif test -d /usr/include/netcdf ; then
    INCLUDES='-I/usr/include/netcdf'
elif test -d /usr/local/netcdf ; then
    INCLUDES='-I/usr/local/netcdf/include'
    LIBS='-L/usr/local/netcdf/lib'
elif test -d /usr/local/include/netcdf.inc ; then
    INCLUDES='-I/usr/local/include'
    LIBS='-L/usr/local/lib'
fi

