#!/bin/bash
#
# $Header: /u/gcmpack/MITgcm/tools/build_options/linux_amd64_ifort+mpi_ice_nas,v 1.5 2010/10/26 18:25:15 heimbach Exp $
# $Name:  $

# tested on pleiades using:
# module load comp-intel/11.1.046 mpi/mpt.1.25 netcdf/3.6.0/intel
#
# Note: option -xSSE4.2 (left commented below) can be used on queue "normal_N"
#  (not compatible with  "normal" queue processors) to get additional speed-up.

FC=ifort

DEFINES='-DALLOW_USE_MPI -DALWAYS_USE_MPI -DWORDLENGTH=4'
CPP='/lib/cpp  -traditional -P'
EXTENDED_SRC_FLAG='-132'
OMPFLAG='-openmp'
CFLAGS='-fPIC'
LDADD='-shared-intel'

LIBS='-L/nasa/sgi/mpt/1.25/lib -lmpi -L/nasa/netcdf/3.6.0/intel/lib -lnetcdf'
INCLUDES='-I/nasa/sgi/mpt/1.25/include -I/nasa/netcdf/3.6.0/intel/include'
INCLUDEDIRS='/nasa/sgi/mpt/1.25/include'
MPIINCLUDEDIR='/nasa/sgi/mpt/1.25/include'
MPI_HEADER_FILES='mpif.h mpiof.h mpif_parameters.h'
MPI_HEADER_FILES_INC='./mpi_headers/mpif.h ./mpi_headers/mpiof.h ./mpi_headers/mpif_parameters.h'

NOOPTFLAGS='-O0 -fPIC'

if test "x$IEEE" = x ; then
    #  No need for IEEE-754
    FFLAGS="$FFLAGS -fPIC -fp-model precise -ftz -w95 -W0 -WB -convert big_endian -assume byterecl"
    FOPTIM='-O2 -align -ip -xSSE4.1'
#   FOPTIM='-O2 -align -ip -xSSE4.2'
    NOOPTFILES='calc_oce_mxlayer.F fizhi_lsm.F fizhi_clockstuff.F'
else
    #  Try to follow IEEE-754
    FFLAGS="$FFLAGS -fPIC -w95 -W0 -WB -convert big_endian -assume byterecl"
    FOPTIM='-O0 -noalign'
fi
#- might want to use '-r8' for fizhi pkg:
#FFLAGS="$FFLAGS -r8"

#- For really big executable (> 2 GB), uncomment following 2 lines
#FFLAGS="$FFLAGS -mcmodel medium -shared-intel"
#CFLAGS='-mcmodel=medium'
