#!/bin/bash
#
# tested on pleiades_n using:
# module purge
# module load  mpi/mpt.1.25
# module load comp/intel/11.0.083_64

CPP='/lib/cpp  -traditional -P'
FC=ifort
DEFINES='-DALLOW_USE_MPI -DALWAYS_USE_MPI -DWORDLENGTH=4 -D_BYTESWAPIO'

LIBS='-L/nasa/sgi/mpt/1.25/lib -lmpi'
INCLUDES='-I/nasa/sgi/mpt/1.25/include'
INCLUDEDIRS='/nasa/sgi/mpt/1.25/include'
MPIINCLUDEDIR='/nasa/sgi/mpt/1.25/include'
MPI_HEADER_FILES='mpif.h mpiof.h mpif_parameters.h'
MPI_HEADER_FILES_INC='./mpi_headers/mpif.h ./mpi_headers/mpiof.h
./mpi_headers/mpif_parameters.h'
PAPIINC='-I/usr/local/include'
PAPILIB='-L/usr/local/lib -lpapi'

# FFLAGS for really big executable
FFLAGS='-132 -r8 -i4 -w95 -W0 -WB -assume byterecl -traceback
-mcmodel medium -shared-intel'
CFLAGS='-mcmodel medium'
# FFLAGS for executable < 2GB
FFLAGS='-132 -r8 -i4 -w95 -W0 -WB -assume byterecl -traceback'
CFLAGS=' '
FOPTIM='-O2 -align -ip'
NOOPTFLAGS='-O0'
NOOPTFILES='global_sum_tile.F'

