#!/bin/bash
#
#  Ed Hill
#
#  tested on faulks, 20030818


CPP='/lib/cpp  -traditional -P'

#  Note that the -mp switch is for ieee "maintain precision" and is
#  roughly equivalent to -ieee
if test "x$IEEE" = x ; then
    FFLAGS='-132 -r8 -i4 -w95 -W0 -WB'
else
    FFLAGS='-mp -132 -r8 -i4 -w95 -W0 -WB'
fi

FOPTIM='-O3 -align'
#P3  FOPTIM     = ( $FOPTIM '-tpp6 -xWKM' ) 
#P4  FOPTIM     = ( $FOPTIM '-tpp7 -xWKM' ) 
LIBS='-lPEPCF90'

FC=ifc
DEFINES='-D_BYTESWAPIO -DWORDLENGTH=4'



