#!/bin/bash
#
# $Header: /u/gcmpack/MITgcm/tools/build_options/linux_amd64_pgf77_ocl,v 1.4 2011/09/13 18:28:04 jmc Exp $
# $Name:  $

# tested on ocl00.awi-bremerhaven.de
# Linux ocl00 2.4.21-261-smp #1 SMP Wed Nov 17 22:05:59 UTC 2004 x86_64 unknown
# pgf77 5.2-4
# Copyright 1989-2000, The Portland Group, Inc.  All Rights Reserved.
# Copyright 2000-2004, STMicroelectronics, Inc.  All Rights Reserved.

CC='pgcc'
FC='pgf77'
LINK='pgf77'

DEFINES='-DWORDLENGTH=4 -DNML_EXTENDED_F77'
CPP='/usr/bin/cpp -P -traditional'
EXTENDED_SRC_FLAG='-Mextend'
GET_FC_VERSION="-V"

if test "x$IEEE" = x ; then
    #  No need for IEEE-754
    FFLAGS="$FFLAGS -byteswapio -Mnodclchk"
    FOPTIM='-tp amd64 -O2 -Munroll'
# -Mvect=cachesize:512000,transform
else
    #  Try to follow IEEE-754
    FFLAGS="$FFLAGS -byteswapio"
    FOPTIM='-tp amd64 -O0 -Munroll -Kieee'
# -Mvect=cachesize:512000,transform
fi
#- might want to use '-r8' for fizhi pkg:
#FFLAGS="$FFLAGS -r8"

INCLUDES='-I/var/tmp.shared/netcdf-64/include'
LIBS='-L/var/tmp.shared/netcdf-64/lib -lnetcdf'

if test "x$MPI" = xtrue ; then
    INCLUDES="-I/opt/scali/include $INCLUDES"
    LIBS="-L/opt/scali/lib64 $LIBS -lfmpi -lmpi"
fi
