#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/linux_ia32_g77,v 1.7 2004/07/30 20:53:25 edhill Exp $
#  $Name:  $
#


FC=g77
CC=gcc
DEFINES='-D_BYTESWAPIO -DWORDLENGTH=4'
CPP='cpp  -traditional -P'
NOOPTFLAGS='-O0'

if test "x$IEEE" = x ; then
    #  No need for IEEE-754
    FFLAGS='-Wimplicit -Wunused -Wuninitialized'
    FOPTIM='-O3 -malign-double -funroll-loops'
else
    #  Try to follow IEEE-754
    FFLAGS='-Wimplicit -Wunused -Wuninitialized -ffloat-store'
    FOPTIM='-O0 -malign-double'
fi

# netcdf
# LIBS="-lnetcdf"

