#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/Attic/nec_sx6_caspur,v 1.1 2004/07/24 01:42:58 heimbach Exp $
#

#cph: DEFINES needs testing
#DEFINES='-DTARGET_CRAY_VECTOR -DTARGET_NEC_VECTOR -DWORDLENGTH=4'
DEFINES='-DWORDLENGTH=1'
FC='f90'
CC='c++'
LINK='f90'
#FFLAGS='-Wf "-pvctl noassume loopcnt=5000000" -Pstack'
FFLAGS= '-ew'
#FOPTIM='-Cvopt'
NOOPTFLAGS='-Cssafe'
NOOPTFILES='barrier.F different_multiple.F external_fields_load.F'
