#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/Attic/o2k_noopt+mpi,v 1.2 2003/08/27 22:12:31 edhill Exp $
#

S64='$(TOOLSDIR)/set64bitConst.sh'
MAKEDEPEND=makedepend
DEFINES='-DWORDLENGTH=4'


INCLUDES='-I/usr/include'
FFLAGS='-n32 -extend_source -bytereclen'
FOPTIM='-O0'
LIBS='-lmpi'
