#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/Attic/osf1_halem_mpi,v 1.1 2003/09/04 17:29:31 edhill Exp $
#

#  confirmed on Halem by eh3, 2003-09-04

LN='ln -s'
S64='$(TOOLSDIR)/set64bitConst.sh'
MAKEDEPEND='mkdep -f depend.out'
DEFINES='-DALLOW_USE_MPI -DALWAYS_USE_MPI -DTARGET_DEC -DWORDLENGTH=1'


CPP='/usr/bin/cpp -P'
#ph: makedepend not available on some/many DEC Alpha's; use mkdep instead
FC='f77'
LINK='f77'
LIBS='-lfmpi -lmpi -lkmp_osfp10 -pthread'
FFLAGS='-convert big_endian -r8 -extend_source -automatic -call_shared -notransform_loops -align dcommons'
FOPTIM='-O5 -fast -tune host -inline all'
#ph: -O5 probably too aggressive in conjunction with adjoint code
NOOPTFILES='barrier.F different_multiple.F external_fields_load.F'
NOOPTFLAGS='-O0'
RMFILES='*.p.out'
