#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/Attic/osf1+mpi,v 1.2 2003/08/27 22:12:31 edhill Exp $
#

S64='$(TOOLSDIR)/set64bitConst.sh'
MAKEDEPEND=makedepend
DEFINES='-DWORDLENGTH=4'


#ph: e.g. halem.gsfc.nasa.gov
LIBS='-lfmpi -lmpi -lkmp_osfp10 -pthread'
#ph: -lkmp_osfp10 not needed on some/many platforms
