#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/Attic/osf1_alpha_f77,v 1.2 2004/07/17 02:05:34 edhill Exp $
#

#  confirmed on Halem by eh3, 2003-09-03

S64='$(TOOLSDIR)/set64bitConst.sh'
DEFINES='-DTARGET_DEC -DWORDLENGTH=1'


CPP='/usr/bin/cpp -P'

#ph: makedepend not available on some/many DEC Alpha's; use mkdep instead
#EH3  Remove the buggy mkdep since the newly included cyrus version
#EH3  works much better on machines such as "halem"
#EH3  MAKEDEPEND='mkdep -f depend.out'

FC='f77'
LINK='f77'
FFLAGS='-convert big_endian -r8 -extend_source -automatic -call_shared -notransform_loops -align dcommons'
FOPTIM='-O5 -fast -tune host -inline all'
#ph: -O5 probably too aggressive in conjunction with adjoint code
NOOPTFILES='barrier.F different_multiple.F external_fields_load.F'
NOOPTFLAGS='-O0'
RMFILES='*.p.out'
