#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/Attic/sp3,v 1.3 2003/11/13 22:03:39 edhill Exp $
#

S64='$(TOOLSDIR)/set64bitConst.sh'
MAKEDEPEND=makedepend
DEFINES='-DWORDLENGTH=4'

# originally from A. Biastoch, SIO.
# e.g. horizon.npaci.edu
INCLUDES='-I/usr/lpp/ppe.poe/include'
#    set CPP        = ( '/lib/cpp' )
FC='mpxlf95'
LINK='mpxlf95'
LIBS=' -L/usr/local/apps/mass -lmass'
#   set FFLAGS     = ( '-extend_source -mp -mpio -bytereclen -r10000 -mips4' )
#    set FOPTIM     = ( '-O3' )
#   set NOOPTFLAGS = ( '-O0' )
#   set NOOPTFILES = ( 'barrier.F different_multiple.F ' \
#                      'external_fields_load.F' )
RMFILES='rii_files'
