#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/Attic/sp4,v 1.3 2003/09/05 00:25:42 edhill Exp $
#

#  tested on bluesky, EH3 2003-09-04
#  using the following invocation:
#    ../../../tools/genmake2 -mods=../code -of=../../../tools/build_options/sp4 -make=gmake


S64='$(TOOLSDIR)/set64bitConst.sh'
MAKEDEPEND=makedepend
DEFINES='-DTARGET_PWR3 -DTARGET_SGI -DWORDLENGTH=4'

#ph: e.g. bluesky.ucar.edu, marcellus.navo.hpc.mil
LN='ln -s'
INCLUDES='-I/usr/lpp/ppe.poe/include'
#    set CPP        = ( '/lib/cpp' )
CPP='/lib/cpp -P'
FC='mpxlf95'
LINK='mpxlf95'
LIBS=' -L/usr/local/apps/mass -lmass'
#   set FFLAGS     = ( '-extend_source -mp -mpio -bytereclen -r10000 -mips4' )
FFLAGS='-qfixed=132 -O3 -qarch=pwr4 -qtune=pwr4 -qcache=auto -qmaxmem=-1 -bmaxdata:0x80000000'
#    set FOPTIM     = ( '-O3' )
#   set NOOPTFLAGS = ( '-O0' )
#   set NOOPTFILES = ( 'barrier.F different_multiple.F ' \
#                      'external_fields_load.F' )
RMFILES='rii_files'
