#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/Attic/sp4+mpi,v 1.2 2005/01/15 01:20:19 ce107 Exp $
#

#  tested on bluesky, ce107 Jan 2005


S64='$(TOOLSDIR)/set64bitConst.sh'
MAKEDEPEND=makedepend
DEFINES='-DALLOW_USE_MPI -DALWAYS_USE_MPI -DTARGET_AIX -DWORDLENGTH=4'

INCLUDES='-I/usr/lpp/ppe.poe/include/thread64'
CPP='/lib/cpp -P'
CC='mpcc_r -q64'
FC='mpxlf95_r -q64'
LINK='mpxlf95_r -q64'
LIBS='-L/usr/local/apps/mass -lmass'
FFLAGS='-qfixed=132' 
if test "x$IEEE" = x ; then
    #  No need for IEEE-754
    FOPTIM='-O3 -qhot -qarch=pwr4 -qtune=pwr4 -qcache=auto -qmaxmem=-1'
else
    #  Try to follow IEEE-754
    FOPTIM='-O3 -qstrict -qarch=pwr4 -qtune=pwr4 -qcache=auto -qmaxmem=-1'
fi
FC_NAMEMANGLE="#define FC_NAMEMANGLE(X) X"

