#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/Attic/sp4+mpi,v 1.1 2005/01/13 00:16:31 ce107 Exp $
#

#  tested on bluesky, ce107 Jan 2005


S64='$(TOOLSDIR)/set64bitConst.sh'
MAKEDEPEND=makedepend
DEFINES='-DALLOW_USE_MPI -DALWAYS_USE_MPI -DTARGET_AIX -DWORDLENGTH=4'

INCLUDES='-I/usr/lpp/ppe.poe/include'
CPP='/lib/cpp -P'
CC='mpcc_r -q64'
FC='mpxlf95 -q64'
LINK='mpxlf95_r -q64'
LIBS='-L/usr/local/apps/mass -lmass'
FFLAGS='-qfixed=132' 
FOPTIM='-O3 -qarch=pwr4 -qtune=pwr4 -qcache=auto -qmaxmem=-1'
FC_NAMEMANGLE="#define FC_NAMEMANGLE(X) X"
