#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/Attic/sp4_edvir1,v 1.1 2005/11/17 12:45:03 mlosch Exp $
#  $Name:  $
# 
# tested on edvir1.awi-bremerhaven.de
# uname -a: AIX edvir1 2 5 0010117A4C00
#

S64='$(TOOLSDIR)/set64bitConst.sh'
MAKEDEPEND=makedepend
DEFINES='-DTARGET_AIX -DWORDLENGTH=4 -DNML_TERMINATOR'

INCLUDES='-I/edvir1/soft/netcdf-3.5.1/64/include'
CPP='/lib/cpp -P'
CC='cc -q64'
FC='xlf95 -q64'
LINK='xlf95 -q64'
LIBS='-L/export/soft/mass/4.1/aix5/lib -lmass -L/edvir1/soft/netcdf-3.5.1/64/lib -lnetcdf'

FFLAGS='-qfixed=132' 
if test "x$IEEE" = x ; then
    #  No need for IEEE-754
    FOPTIM='-O3 -qhot -qarch=pwr4 -qtune=pwr4 -qcache=auto -qmaxmem=-1'
else
    #  Try to follow IEEE-754
    FOPTIM='-O3 -qstrict -qarch=pwr4 -qtune=pwr4 -qcache=auto -qmaxmem=-1'
fi
FC_NAMEMANGLE="#define FC_NAMEMANGLE(X) X"

