#!/bin/bash
#
# $Header: /u/gcmpack/MITgcm/tools/build_options/sp6_ncar,v 1.1 2010/09/08 22:36:39 ce107 Exp $
# $Name:  $

S64='$(TOOLSDIR)/set64bitConst.sh'
MAKEDEPEND=makedepend

DEFINES='-DTARGET_AIX -DWORDLENGTH=4 -DNML_TERMINATOR'

INCLUDES='-I/contrib/netcdf-3.6.2/include'
CPP='/lib/cpp -P'
CC='xlc_r -q64'
FC='xlf_r -q64'
LINK='xlf_r -q64'
LIBS='-lmass -L/contrib/netcdf-3.6.2/lib'
FFLAGS='-qfixed=132'
if test "x$IEEE" = x ; then
    #  No need for IEEE-754
    FOPTIM='-O3 -Q -qarch=pwr6 -qtune=pwr6 -qcache=auto -qmaxmem=-1'
    CFLAGS='-O3 -Q -qarch=pwr6 -qtune=pwr6 -qcache=auto -qmaxmem=-1'
else
    #  Try to follow IEEE-754
    FOPTIM='-O3 -qstrict -Q -qarch=pwr6 -qtune=pwr6 -qcache=auto -qmaxmem=-1'
    CFLAGS='-O3 -qstrict -Q -qarch=pwr6 -qtune=pwr6 -qcache=auto -qmaxmem=-1'
fi
FC_NAMEMANGLE="#define FC_NAMEMANGLE(X) X"

HPMTINC=''
HPMTLIB='-lhpm_r -lpmapi'
GSLINC='-I/contrib/gsl-1.12/include'
GSLLIB='-L/contrib/gsl-1.12/gsl-1.5/lib64 -lgsl -lgslcblas'
PAPIINC='-I/contrib/papi-3.6.2/include'
PAPILIB='-L/contrib/papi-3.6.2/lib -lpapi -lpmapi'

