#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/sunos_sun4u_g77,v 1.2 2004/03/01 18:29:54 edhill Exp $
#  $Name:  $
#


FC=g77
#DEFINES='-D_BYTESWAPIO -DWORDLENGTH=4'
DEFINES='-DWORDLENGTH=4'
CPP='cpp  -traditional -P'
NOOPTFLAGS='-O0'
AWK='gawk'
MAKE='gmake'

# netcdf
# LIBS="-lnetcdf"

#  For IEEE, use the "-ffloat-store" option
if test "x$IEEE" = x ; then
    FFLAGS='-Wimplicit -Wunused -Wuninitialized'
    FOPTIM='-O3 -funroll-loops'
else
    FFLAGS='-Wimplicit -Wunused -ffloat-store'
    FOPTIM='-O0'
fi


