#!/bin/bash
#
# $Header: /u/gcmpack/MITgcm/tools/build_options/sunos_amd64_f77_awi,v 1.1 2007/01/16 15:12:03 mlosch Exp $
# $Name:  $  
#
# tested on 
# SunOS testopt2 5.10 Generic_118855-19 i86pc i386 i86pc
# with f77: Sun Fortran 95 8.2 Patch 121019-01 2005/11/22

FC_NAMEMANGLE="#define FC_NAMEMANGLE(X) X ## _"
S64='$(TOOLSDIR)/set64bitConst.sh'
DEFINES='-D_BYTESWAPIO -DWORDLENGTH=4'
#AWK='gawk'
MAKEDEPEND='$(TOOLSDIR)/cyrus-imapd-makedepend/makedepend'
#MAKEDEPEND='$(TOOLSDIR)/xmakedepend'
#MAKE='gmake'
CPP='/usr/ccs/lib/cpp -P'
# this one works, too
#CPP='/opt/sfw/bin/cpp -traditional -P'
FC='f77'
# This is an example of how to specify where your 
# netcdf libraries and include files are; 
# in this particular example, they are in 
# /usr/local/libs and /usr/local/include and the netcdf libraries in
# /opt/netcdf/Sun-cc
INCLUDES='-I/usr/local/include -I/opt/netcdf/Sun-cc/include'
LIBS='-L/usr/local/lib -L/opt/netcdf/Sun-cc/lib'

if test "x$IEEE" = x ; then
    #  No need for IEEE-754
    FFLAGS='-stackvar -explicitpar -vpara -e -u -noautopar -xtypemap=real:64,double:64,integer:32'
    FOPTIM='-dalign -O4 -xarch=native -fsimple=2'
    CFLAGS='-dalign -xO4 -xarch=native'
else
    #  Try to follow IEEE-754
    FFLAGS='-e -u -xtypemap=real:64,double:64,integer:32 -fsimple=0'
    FOPTIM='-O0'
    CFLAGS='-xO0'
fi
NOOPTFLAGS='-dalign -O0'
