#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/Attic/sunos+mpi,v 1.3 2003/11/13 22:03:39 edhill Exp $
#

S64='$(TOOLSDIR)/set64bitConst.sh'
MAKEDEPEND=makedepend
DEFINES='-DWORDLENGTH=4'

CPP='/usr/ccs/lib/cpp -P'
INCLUDES='-I/usr/local/mpi/include'
FFLAGS='-stackvar -explicitpar -vpara -e -u -noautopar -xtypemap=real:64,double:64,integer:32 -fsimple=0'
FOPTIM='-dalign -O3 -xarch=v9'
NOOPTFLAGS='-dalign -O0 -xarch=v9'
