#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/sunos_sun4u_f77,v 1.7 2005/02/28 08:47:36 mlosch Exp $
#  $Name:  $  
#
# tested on 
# SunOS model.awi-bremerhaven.de 5.9 Generic_112233-11 sun4u sparc SUNW,Sun-Fire-15000
# SunOS tphs14.awi-bremerhaven.de 5.8 Generic_117350-08 sun4u sparc SUNW,Sun-Blade-1000
# with f90: Forte Developer 7 Fortran 95 7.0 Patch 111714-03 2002/11/19


FC_NAMEMANGLE="#define FC_NAMEMANGLE(X) X ## _"
S64='$(TOOLSDIR)/set64bitConst.sh'
DEFINES='-DWORDLENGTH=4'
#AWK='gawk'
MAKEDEPEND='$(TOOLSDIR)/cyrus-imapd-makedepend/makedepend'
#MAKEDEPEND='$(TOOLSDIR)/xmakedepend'
#MAKE='gmake'
CPP='/usr/ccs/lib/cpp -P'
# this one works, too
#CPP='/opt/sfw/bin/cpp -traditional -P'
FC='f77'
# This is an example of how to specify where your 
# netcdf libraries and include files are; 
# in this particular example, they are in 
# /usr/local/libs and /usr/local/include.
INCLUDES='-I/usr/local/include'
LIBS='-L/usr/local/lib'

if test "x$IEEE" = x ; then
    #  No need for IEEE-754
    FFLAGS='-stackvar -explicitpar -vpara -e -u -noautopar -xtypemap=real:64,double:64,integer:32'
    FOPTIM='-dalign -O4 -xarch=native -fsimple=2'
    CFLAGS='-dalign -xO4 -xarch=native'
else
    #  Try to follow IEEE-754
    FFLAGS='-e -u -xtypemap=real:64,double:64,integer:32 -fsimple=0'
    FFLAGS='-e -u -xtypemap=real:64,double:64,integer:32 -fsimple=0'
    FOPTIM='-O0'
    CFLAGS='-xO0'
fi
NOOPTFLAGS='-dalign -O0'
