#!/bin/bash
#
# $Header: /u/gcmpack/MITgcm/tools/build_options/SUPER-UX_SX-6_f90+mpi_caspur,v 1.2 2010/03/21 22:22:53 jmc Exp $
# $Name:  $

# adapted to nec.caspur.it

DEFINES='-DWORDLENGTH=1'
FC='f90'
CC='c++'
LINK='f90'
#FFLAGS='-Wf "-pvctl noassume loopcnt=5000000" -Pstack'
FFLAGS= '-ew'
FOPTIM='-Chopt'
NOOPTFLAGS='-Cssafe'
NOOPTFILES='barrier.F different_multiple.F external_fields_load.F'
