#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/Attic/SUPER-UX_SX-8_sxf90+mpi_awi,v 1.5 2007/09/25 19:28:19 mlosch Exp $
#
# for cross compiling on sx8.awi.de
# uname -a: 
# Linux sx8 2.6.5-7.282-default #1 SMP Tue Aug 29 10:40:40 UTC 2006 ia64 ia64 ia64 GNU/Linux#

# nec use
CPP='/lib/cpp -traditional -P'
DEFINES='-DALLOW_USE_MPI -DALWAYS_USE_MPI -DTARGET_NEC_SX -DWORDLENGTH=1 -UHAVE_SIGREG -DSEAICE_VECTORIZE_LSR'
FC='sxmpif90'
CC='sxcc -sx8r'

RMFILES='*.L'
FC_NAMEMANGLE="#define FC_NAMEMANGLE(X)  X ## _"
LINK='sxmpif90'
#LINK='sxmpif90 -p' # with profiler
FFLAGS='-Pstack -sx8r'
# additional options:
# include a formated code and a listing of compiler transformations 
# in *.L files
#FFLAGS=$FFLAGS' -R2'
# assume a loop count of 5,000,000 instead of estimating it from field
# declarations and include details messages about vectorization (if -R2 
# specified)
#FFLAGS=$FFLAGS' -Wf "-pvctl noassume loopcnt=5000000 fullmsg"'
# This is how you inline routines (the actual routines depend on the packages 
# used, therefore there are only a few examples here;
# edit this list in the Makefile, because including it here will break the
# various tests in genmake2, maybe I will find a better way to do this
# later)
#FFLAGS=$FFLAGS' -pi fullmsg exp=timestep_tracer,ilnblnk,ifnblnk,cycle_tracer,pressure_for_eos rexp=bar2,fool_the_compiler expin=timestep_tracer.F,fool_the_compiler.F,bar2.F,utils.F,cycle_tracer.F,pressure_for_eos.F'
# define basic storage unit as 8 bytes (default is 4); does not work with 
# netCDF (library needs recompilation, accordingly)
#FFLAGS=$FFLAGS' -ew'   
# trace output for performance analysis
#FFLAGS=$FFLAGS' -ftrace'
# default automatic optimization level
#FOPTIM='-C vopt' 
# highest automatic optimization level, handle with care
FOPTIM='-C hopt'

# these files require lower optimization
NOOPTFILES='ini_forcing.F mom_calc_visc.F'
NOOPTFLAGS='-C vopt'

# awi specific paths and stuff
INCLUDES='-I/SX/usr/include -I/home/sx8/sx8bench/netcdf/include'
LIBS='-L/home/sx8/sx8bench/netcdf/lib -lnetcdf'
