#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/Attic/sv1,v 1.4 2004/07/19 22:06:50 heimbach Exp $
#

S64='$(TOOLSDIR)/set64bitConst.sh'
MAKEDEPEND=makedepend
DEFINES='-DWORDLENGTH=4 -DTARGET_CRAY_VECTOR'

FC='f90'
LINK='f90'
CPP='/opt/ctl/bin/cpp -N -P'
FOPTIM='-O0'
NOOPTFLAGS='-O0'
