#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/Attic/sv1,v 1.3 2003/11/13 22:03:39 edhill Exp $
#

S64='$(TOOLSDIR)/set64bitConst.sh'
MAKEDEPEND=makedepend
DEFINES='-DWORDLENGTH=4'

FC='f90'
LINK='f90'
CPP='/opt/ctl/bin/cpp -N -P'
FOPTIM='-O0'
NOOPTFLAGS='-O0'
