#!/bin/bash
#
# o -N Job Name
#PBS -N eh3_intel
#
#PBS -q four-twelve
#
# o -l ask for 3 nodes, each with the attribute "p4".
#PBS -l nodes=2:p4
#
# o Where to write output
#PBS -e /cluster/home/edhill/err_intel
#PBS -o /cluster/home/edhill/out_intel
#
# o Export all my environment variables to the job
#PBS -V
#

VENDOR=intel
MF="mf_"$VENDOR
RUNIT="runit_"$VENDOR
cd ~edhill
HERE=`pwd`
cat $PBS_NODEFILE > $MF
NCPU=`wc -l $MF | awk '{print $1}'`
MPI="/usr/local/pkg/mpi/mpi-1.2.4..8a-gm-1.5/"$VENDOR"/bin/mpirun.ch_gm"
EXE="$MPI -machinefile $HERE/$MF --gm-kill 5 -v -np $NCPU ./mitgcmuv"

cat << EOF > $RUNIT
#!/bin/bash

$EXE

#cp STDOUT.0000 output.txt

EOF
chmod a+x $RUNIT

COMMAND="$HERE/$RUNIT"

# cat << EOF > $HERE"/.cvspass"
# /1 :pserver:cvsanon@mitgcm.org:2401/u/gcmpack Ah<Zy=0=
# EOF
TDIR="/SCRATCH/s06/edhill/tmp_"$VENDOR
if test -e $TDIR ; then
    rm -rf $TDIR
fi
mkdir $TDIR
cd $TDIR
cvs -d :pserver:cvsanon@mitgcm.org:/u/gcmpack co MITgcm
#  cvs co MITgcm
cd MITgcm/verification
#OPTFILE="../tools/build_options/linux_ia32_"$VENDOR"+mpi_cg01"
OPTFILE="../tools/build_options/linux_ia32_ifc+mpi_cg01"
./testreport -mpi -of $OPTFILE -command $COMMAND -odir "cg01_"$VENDOR -a 'edhill@mitgcm.org'


