#! /usr/bin/env bash

#  $Header: /u/gcmpack/MITgcm/verification/fizhi-gridalt-hs/input/prepare_run,v 1.1 2006/11/23 23:32:36 jmc Exp $
#  $Name:  $
 
#- in order to save disc space, take *.bin files
#- from this dir:
fromDir="../../fizhi-cs-32x32x10/input"

fileList=`( cd $fromDir ; ls data.gcmo3 TSMo3.v02.gra tile00?.mitgrid )`

#echo 'fileList=' $fileList

#- and do a symbolic link in the current directory 
#   (if the file does not already exist)
if test -d $fromDir ; then
  lnkList='files:'
  for xx in $fileList
  do
    if test -r ${fromDir}/$xx ; then 
      if test ! -r $xx ; then 
        lnkList=${lnkList}" "$xx
        ln -sf ${fromDir}/$xx .
      fi
    fi
  done
  echo ' link' $lnkList "from dir:" $fromDir
else
  echo " Error:" $fromDir "not a directory"
fi
