#! /bin/sh

#-- Import input files from experiment aim.5l_cs/input.thSI/
#   this reduce the disk space required when downloading this set-up

impDir='../../aim.5l_cs/input.thSI'
dirAtm=`pwd`

echo 'Import Input files from dir:' $impDir
echo ''
cd $impDir

listF=`ls *.bin`
for xx in $listF
do
 if test -f $dirAtm/$xx
 then echo 'file' $xx ' already exists'
 else echo ' cp ' $xx
  cp -p -i $xx $dirAtm
 fi 
done

cd $dirAtm
