#! /bin/sh

#-- Used the same grid definition and files than the ocean:
#   copy CS grid-file from ../input_ocn 
#   this reduce the disk space required when downloading this set-up

if test $# = 1
then
 impDir=$1
else
 impDir='../input_ocn'
fi
dirAtm=`pwd`

echo 'Import CS-grid files from dir:' $impDir

cd $impDir
#listF=`ls RA*.bin DX?.bin DY?.bin LON?.bin LAT?.bin`
listF=`ls *.mitgrid`
echo ' list of files:' $listF


for xx in $listF
do
 if test -f $dirAtm/$xx
 then echo 'file' $xx 'already exists'
 else echo ' cp ' $xx
  cp -p -i $xx $dirAtm
 fi 
done

cd $dirAtm
