#! /usr/bin/env sh
#
# $Header: /u/gcmpack/MITgcm/pkg/mnc/parse_local_info,v 1.2 2005/01/05 18:26:56 edhill Exp $
#

tag="../../doc/tag-index"
if test -r $tag ; then
    a=`cat $tag | grep '^.Header:' | awk '{print $3 " " $4}'`
else
    a="unknown"
fi
echo "#define MNC_TAG_ID '$a'"

