#! /usr/bin/env sh
#
# $Header: /u/gcmpack/MITgcm/pkg/mnc/parse_local_info,v 1.3 2007/10/08 17:00:17 jmc Exp $
# $Name:  $
#

tag="../../doc/tag-index"
if test -r $tag ; then
    a=`cat $tag | grep '^.Header:' | awk '{print $3 " " $4}'`
else
    a="unknown"
fi
echo "#define MNC_TAG_ID '$a'"

