#! /usr/bin/env bash

#- in order to save disc space, take *.bin files
#- from this dir:
fromDir="../../tutorial_global_oce_latlon/input"

fileList=`( cd $fromDir ; echo *.bin )`

#echo 'fileList=' $fileList

#- and do a symbolic link in the current directory
#   (if the file does not already exist)
if test -d $fromDir ; then
  lnkList='files:'
  for xx in $fileList
  do
    if test -r ${fromDir}/$xx ; then
      if test ! -r $xx ; then
        lnkList=${lnkList}" "$xx
        ln -sf ${fromDir}/$xx .
      #- SST file: copy last month (=Dec) and append to the beginning
        if test $xx == 'lev_sst.bin' ; then
          yy='lev_sst'
          dd if=$xx bs=14400 count=1 skip=11 of=${yy}_dec.tmp
          cat ${yy}_dec.tmp $yy.bin > ${yy}_startdec.tmp
         #rm -rf ${yy}_dec.tmp
        fi
      fi
    fi
  done
  echo ' link' $lnkList "from dir:" $fromDir
else
  echo " Error:" $fromDir "not a directory"
fi

