#! /usr/bin/env bash

#- in order to save disc space, take *.bin files
#- from this dir:
fromDir="../../tutorial_global_oce_latlon/input"

fileList=`( cd $fromDir ; echo *.bin )`

#echo 'fileList=' $fileList

#- and do a symbolic link in the current directory 
#   (if the file does not already exist)
if test -d $fromDir ; then
  lnkList='files:'
  for xx in $fileList
  do
    if test -r ${fromDir}/$xx ; then 
      if test ! -r $xx ; then 
        lnkList=${lnkList}" "$xx
        ln -sf ${fromDir}/$xx .
      fi
    fi
  done
  xx=lev_sst
  dd if=$xx.bin bs=14400 count=1 skip=11 of=${xx}_dec.bin
  cat ${xx}_dec.bin $xx.bin >${xx}_startdec.bin
  echo ' link' $lnkList "from dir:" $fromDir
else
  echo " Error:" $fromDir "not a directory"
fi

