#!/bin/bash

# $Header: /u/gcmpack/MITgcm/verification/cpl_aim+ocn/build_atm/genmake_local,v 1.1 2003/12/15 21:06:01 jmc Exp $

#  This is the local options file for the "new" version of genmake
#
#  EH3 initial version 2003-08

MODS="../code_atm ../shared_code"
