#!/bin/bash

#  Ed Hill
#  Wed Nov 19 18:31:21 EST 2003

if test -e ./build_dir ; then
    rm -rf ./build_dir
fi
mkdir ./build_dir

db2ps -d ldp.dsl devel_HOWTO.sgml
db2pdf -d ldp.dsl devel_HOWTO.sgml
mv devel_HOWTO.pdf devel_HOWTO.ps ./build_dir

rm -rf devel_HOWTO
db2html -d ./ldp.dsl devel_HOWTO.sgml
( cd devel_HOWTO && ln -s t1.htm index.html )
mv devel_HOWTO ./build_dir/devel_HOWTO_multipage/

db2html -u -d ./ldp.dsl devel_HOWTO.sgml
( cd devel_HOWTO && mv devel_HOWTO.html index.html )
mv devel_HOWTO ./build_dir/devel_HOWTO_onepage/

(
    cd ./build_dir
    ln -s devel_HOWTO_multipage html_multipage
    ln -s devel_HOWTO_onepage html_onepage
)

ssh mitgcm.org 'cd /u/httpd/html/devel_HOWTO ; rm -rf dev* html*'
scp -r ./build_dir/* mitgcm.org:/u/httpd/html/devel_HOWTO
ssh mitgcm.org 'chgrp -R gcmpack /u/httpd/html/devel_HOWTO/*'

