#!/bin/bash

# $Header: /u/gcmpack/MITgcm/doc/install_devel_HOWTO,v 1.6 2011/04/24 00:01:05 jmc Exp $
# $Name:  $

set -x
scp ./devel_HOWTO.ps mitgcm.org:/u/httpd/html/public/devel_HOWTO
scp ./devel_HOWTO.pdf mitgcm.org:/u/httpd/html/public/devel_HOWTO
scp ./devel_HOWTO_onepage/index.html mitgcm.org:/u/httpd/html/public/devel_HOWTO/devel_HOWTO_onepage
scp ./devel_HOWTO_multipage/*.htm* mitgcm.org:/u/httpd/html/public/devel_HOWTO/devel_HOWTO_multipage
#ssh mitgcm.org 'chgrp -R gcmpack /u/httpd/html/public/devel_HOWTO/devel_HOWTO.p*'
#ssh mitgcm.org 'chgrp -R gcmpack /u/httpd/html/public/devel_HOWTO/devel_HOWTO_*/*.htm*'

