#! /usr/bin/env bash

#- in order to save disc space, take files:
fileList="tile001.mitgrid tile002.mitgrid tile003.mitgrid tile004.mitgrid tile005.mitgrid tile006.mitgrid"
#- from this dir:
fromDir="../../aim.5l_cs/input"

#- and do a symbolic link in the current directory 
#   (if the file does not already exist)
if test -d $fromDir ; then
  lnkList='files:'
  for xx in $fileList
  do
    if test -r ${fromDir}/$xx ; then 
      if test ! -r $xx ; then 
        lnkList=${lnkList}" "$xx
        ln -sf ${fromDir}/$xx .
      fi
    fi
  done
  echo ' link' $lnkList "from dir:" $fromDir
else
  echo " Error:" $fromDir "not a directory"
fi
