#!/bin/bash

# $Header: /u/gcmpack/MITgcm/verification/front_relax/input/Attic/gm_local,v 1.1 2003/08/16 14:01:09 edhill Exp $

#  This is the local options file for the "new" version of genmake 
#
#  EH3 initial version 2003-08


DISABLE="aim kpp zonal_filt obcs timeave zonal_filt"

