#!/bin/bash
#
#PBS -q four-twelve
#PBS -N tst_gnu
#PBS -l nodes=2:ppn=2
#PBS -e /home/jmc/test_ACES/output/tst_gnu.stderr
#PBS -o /home/jmc/test_ACES/output/tst_gnu.stdout
 
# $Header: /u/gcmpack/MITgcm/tools/example_scripts/ACESgrid/Attic/aces_test_gnu_mpi,v 1.4 2008/01/25 15:17:20 jmc Exp $
# $Name:  $

umask 0022
TST_DIR="/home/jmc/test_ACES/gcm_tests"
HERE='/home/jmc/test_ACES/output'
cd $HERE

if test -f /etc/profile.d/modules.sh ; then
    . /etc/profile.d/modules.sh
fi

sfx='gnu'
module add mpich/$sfx
OPTFILE="../tools/build_options/linux_ia32_g77+mpi_aces"
options='-j 2 -mpi'

MF=$HERE"/mf_"$sfx
cat $PBS_NODEFILE | sort | uniq > $MF
NCPU=`wc -l $MF | awk '{print $1}'`
EXE="mpirun -machinefile $MF -v -np $NCPU ./mitgcmuv"

# cat << EOF > $HERE"/.cvspass"
# /1 :pserver:cvsanon@mitgcm.org:2401/u/gcmpack Ah<Zy=0=
# EOF
gcmDIR="MITgcm_$sfx"
cd $TST_DIR
if test -e $gcmDIR ; then
    rm -rf $gcmDIR
fi
cvs -d :pserver:cvsanon@mitgcm.org:/u/gcmpack co -P -d $gcmDIR MITgcm > /dev/null 2>&1
#  cvs co MITgcm
/usr/bin/find $gcmDIR -type d | xargs chmod g+rxs
/usr/bin/find $gcmDIR -type f | xargs chmod g+r

cd $gcmDIR/verification
echo ./testreport $options -of $OPTFILE -command "$EXE" -odir aces-$sfx
./testreport $options -of $OPTFILE -command "$EXE" -odir aces-$sfx

