#!/bin/bash
#
#PBS -q long
#PBS -N tst_mth
#PBS -l nodes=1:ppn=2
#PBS -e /home/jmc/test_ACES/output/tst_mth.stderr
#PBS -o /home/jmc/test_ACES/output/tst_mth.stdout
# #PBS -V
#  ^- commented out => do not export env. variable !
#  since head node environment (& module) is too different from computer node
 
# $Header: /u/gcmpack/MITgcm/tools/example_scripts/ACESgrid/Attic/aces_test_ifc_mth,v 1.1 2007/08/07 18:24:43 jmc Exp $
# $Name:  $

if test -f /etc/profile.d/modules.sh ; then
    . /etc/profile.d/modules.sh
fi
module add ifc/9.0.021 icc/9.0.021 intel/9.0
export OMP_NUM_THREADS=2
export KMP_STACKSIZE=400m

TST_DIR="/home/jmc/test_ACES/gcm_tests"
HERE='/home/jmc/test_ACES/output'
cd $HERE

FC=ifort

# cat << EOF > $HERE"/.cvspass"
# /1 :pserver:cvsanon@mitgcm.org:2401/u/gcmpack Ah<Zy=0=
# EOF
umask 0022
tmpDIR=${TST_DIR}"/tmp_mth"
if test -e $tmpDIR ; then
    rm -rf $tmpDIR
fi
mkdir $tmpDIR
cd $tmpDIR
cvs -d :pserver:cvsanon@mitgcm.org:/u/gcmpack co -P MITgcm > /dev/null 2>&1
#  cvs co MITgcm
/usr/bin/find $tmpDIR -type d | xargs chmod g+rxs
/usr/bin/find $tmpDIR -type f | xargs chmod g+r

cd MITgcm/verification
OPTFILE="../tools/build_options/linux_ia32_"$FC".aces+mth"
# ./testreport -j 2 -mth -of $OPTFILE -command "$EXE" -a 'edhill@mitgcm.org'
echo ./testreport -j 2 -mth -of $OPTFILE
./testreport -j 2 -mth -of $OPTFILE

