#!/bin/bash
#
#PBS -q four-twelve
#PBS -N tst_pgi
#PBS -l nodes=2:ppn=2
#PBS -e /home/jmc/test_ACES/output/tst_pgi.stderr
#PBS -o /home/jmc/test_ACES/output/tst_pgi.stdout
 
# $Header: /u/gcmpack/MITgcm/tools/example_scripts/ACESgrid/Attic/aces_test_pgi_mpi,v 1.8 2008/08/28 18:35:42 jmc Exp $
# $Name:  $

umask 0022
TST_DIR="/home/jmc/test_ACES/gcm_tests"
HERE='/home/jmc/test_ACES/output'
cd $HERE

if test -f /etc/profile.d/modules.sh ; then
    . /etc/profile.d/modules.sh
fi

sfx='pgi'
module add mpich/$sfx
OPTFILE="../tools/build_options/linux_ia32_pgf77+mpi_aces"
options='-mpi -match 10'

checkOut=1
#options="$options -nc" ; checkOut=0
#options="$options -q"  ; checkOut=0

MF=$HERE"/mf_"$sfx
cat $PBS_NODEFILE | sort | uniq > $MF
NCPU=`wc -l $MF | awk '{print $1}'`
EXE="mpirun -machinefile $MF -v -np $NCPU ./mitgcmuv"

# cat << EOF > $HERE"/.cvspass"
# /1 :pserver:cvsanon@mitgcm.org:2401/u/gcmpack Ah<Zy=0=
# EOF
gcmDIR="MITgcm_$sfx"
cd $TST_DIR
#- check for disk space:
dsp=`df . | tail -1 | awk '{print $5}' | sed 's/%$//'`
if [ $dsp -gt 99 ] ; then
  echo 'Not enough space on this disk => do not run testreport.'
  df .
  exit
fi
if [ $checkOut -eq 1 ] ; then
  if test -d $gcmDIR/CVS ; then
    echo "cvs update of dir $gcmDIR :"
    ( cd $gcmDIR ; cvs -q -d :pserver:cvsanon@mitgcm.org:/u/gcmpack update -P -d )
    /bin/rm -rf $gcmDIR/verification/tr_aces-${sfx}_????????_?
  else
    echo "no dir: $gcmDIR/CVS => try a fresh check-out"
    checkOut=2
  fi
fi
if [ $checkOut -eq 2 ] ; then
  if test -e $gcmDIR ; then
     rm -rf $gcmDIR
  fi
  cvs -d :pserver:cvsanon@mitgcm.org:/u/gcmpack co -P -d $gcmDIR MITgcm > /dev/null 2>&1
# cvs co MITgcm
  /usr/bin/find $gcmDIR -type d | xargs chmod g+rxs
  /usr/bin/find $gcmDIR -type f | xargs chmod g+r
else
  if test -e $gcmDIR/verification ; then
     echo "dir $gcmDIR/verification exist"
  else
     echo "no dir $gcmDIR/verification => exit"
     exit
  fi
fi

cd $gcmDIR/verification
echo ./testreport $options -of $OPTFILE -command \"$EXE\" -odir aces-$sfx
./testreport $options -of $OPTFILE -command "$EXE" -odir aces-$sfx

