#!/bin/bash

# $Header: /u/gcmpack/MITgcm/tools/example_scripts/ACESgrid/Attic/check_mp2,v 1.1 2010/12/14 21:34:45 jmc Exp $
# $Name:  $


sfx='mp2'
#EXE="mpiexec -pernode -comm pmi -np $NCPU ./mitgcmuv"
longChk=600
longChk=300
shortChk=60
pNam='mpiexec'
uNam=$USER
HERE=`pwd`
pLog="kill_$sfx.log"

echo "start $0 from $HERE at:" `date` "by user: $uNam"
#uNam='jmc' ; HERE='/home/jmc/test_ACES/output' ; cd $HERE

while test ! -f stop_check_$sfx
do
  sleep $longChk
  # check for defunct proc
  nZ=`ps wauxx | grep $uNam | grep $pNam | grep '<defunct>' | wc -l`
  if [ $nZ -ge 1 ] ; then
    echo "found $nZ $pNam zombie processes at:" `date`
    listZ=`ps wauxx | grep $uNam | grep $pNam | grep '<defunct>' | awk '{print $2}'`
    sleep $shortChk
    for p1Z in $listZ ; do
      p2Z=`ps -f -p $p1Z | grep $pNam | grep '<defunct>' | awk '{print $2}'`
      if test "x$p2Z" = "x$p1Z" ; then
        #-- report to permanent log file
        echo '--------------------' >> $pLog
        date >> $pLog ; uname -a >> $pLog
        ps -f -p $p1Z >> $pLog
        #--
        ppZ=`ps -f -p $p1Z | grep $pNam | awk '{print $3}'`
        echo " try to kill parent proc: $ppZ at:" `date` | tee -a $pLog
        kill -9 $ppZ
        out=$?
        echo " return code: $out" | tee -a $pLog
        ps wauxx | grep $uNam | grep $pNam | tee -a $pLog
        echo '--------------------' >> $pLog
      else
        echo " proc: $p1Z no more Zombie at:" `date`
      fi
    done
    nZ=`ps wauxx | grep $uNam | grep $pNam | grep '<defunct>' | wc -l`
    echo " $nZ $pNam zombie process remain at:" `date`
  fi
done
ls -l stop_check_$sfx
exit
