#!/bin/bash
#
#PBS -q long
#PBS -N eh3_pgf77
#PBS -l nodes=2:ppn=2
#PBS -e /home/edhill/test_outp/eh3_pgi.stderr
#PBS -o /home/edhill/test_outp/eh3_pgi.stdout
#PBS -V
 
if test -f /etc/profile.d/modules.sh ; then
    . /etc/profile.d/modules.sh
fi
module add mpich/pgi

HERE='/home/edhill/test_outp'
cd $HERE

FC=pgf77
MF=$HERE"/mf_"$FC
cat $PBS_NODEFILE | sort | uniq > $MF
NCPU=`wc -l $MF | awk '{print $1}'`
EXE="mpirun -machinefile $MF -v -np $NCPU ./mitgcmuv"

# cat << EOF > $HERE"/.cvspass"
# /1 :pserver:cvsanon@mitgcm.org:2401/u/gcmpack Ah<Zy=0=
# EOF
umask 0022
TDIR="/net/ds-01/scratch-5/edhill/tmp_"$FC
if test -e $TDIR ; then
    rm -rf $TDIR
fi
mkdir $TDIR
cd $TDIR
cvs -d :pserver:cvsanon@mitgcm.org:/u/gcmpack co -P MITgcm > /dev/null 2>&1
#  cvs co MITgcm
/usr/bin/find $TDIR -type d | xargs chmod g+rxs
/usr/bin/find $TDIR -type f | xargs chmod g+r

cd MITgcm/verification
OPTFILE="../tools/build_options/linux_ia32_"$FC"+mpi_aces"
# ./testreport -j 2 -mpi -of $OPTFILE -command "$EXE" -a 'edhill@mitgcm.org'
./testreport -mpi -of $OPTFILE -command "$EXE"

