#!/bin/bash
#
#PBS -q long
#PBS -N eh3_mth
#PBS -l nodes=1:ppn=2
#PBS -e /home/edhill/test_outp/eh3_mth.stderr
#PBS -o /home/edhill/test_outp/eh3_mth.stdout
#PBS -V
 
if test -f /etc/profile.d/modules.sh ; then
    . /etc/profile.d/modules.sh
fi
module add ifc/9.0.021 icc/9.0.021 intel/9.0
export OMP_NUM_THREADS=2
export KMP_STACKSIZE=400m

HERE='/home/edhill/test_outp'
cd $HERE

FC=ifort

# cat << EOF > $HERE"/.cvspass"
# /1 :pserver:cvsanon@mitgcm.org:2401/u/gcmpack Ah<Zy=0=
# EOF
umask 0022
TDIR="/net/ds-01/scratch-5/edhill/tmp_mth"
if test -e $TDIR ; then
    rm -rf $TDIR
fi
mkdir $TDIR
cd $TDIR
cvs -d :pserver:cvsanon@mitgcm.org:/u/gcmpack co -P MITgcm > /dev/null 2>&1
#  cvs co MITgcm
/usr/bin/find $TDIR -type d | xargs chmod g+rxs
/usr/bin/find $TDIR -type f | xargs chmod g+r

cd MITgcm/verification
OPTFILE="../tools/build_options/linux_ia32_"$FC".aces+mth"
# ./testreport -j 2 -mth -of $OPTFILE -command "$EXE" -a 'edhill@mitgcm.org'
echo ./testreport -j 2 -mth -of $OPTFILE
./testreport -j 2 -mth -of $OPTFILE

