#!/bin/bash
#
#PBS -q four
#PBS -N tst_tuv
#PBS -l nodes=1:ppn=2
#PBS -e /mit/jm_c/test_acesgrid/output/tst_tuv.stderr
#PBS -o /mit/jm_c/test_acesgrid/output/tst_tuv.stdout

# $Header: /u/gcmpack/MITgcm/tools/example_scripts/ACESgrid/Attic/test_aces_op64_tuv,v 1.3 2011/08/24 12:58:00 jmc Exp $
# $Name:  $

if test -f /etc/profile.d/modules.sh ; then
    . /etc/profile.d/modules.sh
fi
# Note: added "ulimit -s unlimited" in file "~/.tcshrc"
# to pass big test (the 2 fizhi-cs-* test & adjoint tests) with MPI

umask 0022
#- to get case insensitive "ls" (and order of tested experiments)
export LC_ALL="en_US.UTF-8"

#TST_DIR="/home/jmc/test_ACES"
TST_DIR="/mit/jm_c/test_acesgrid"
HERE=$TST_DIR/output
#cd $HERE

sfx='tuv'
 module add open64
 OPTFILE="../tools/build_options/linux_amd64_open64"
 options="-j 2 -devel"
#options="-j 2 -mth -gsl"
#export OMP_NUM_THREADS=2
#export OMP_SLAVE_STACK_SIZE=400m
#export GSL_IEEE_MODE=double-precision,mask-underflow,mask-denormalized
 ulimit -s unlimited

#dAlt=`date +%d` ; dAlt=`expr $dAlt % 3`
#if [ $dAlt -eq 1 ] ; then options="$options -fast" ; fi

checkOut=1
#options="$options -nc" ; checkOut=0
#options="$options -q"  ; checkOut=0

gcmDIR="MITgcm_$sfx"
cd $TST_DIR
#- check for disk space:
dsp=`df -P . | tail -1 | awk '{print $5}' | sed 's/%$//'`
if [ $dsp -gt 99 ] ; then
  echo 'Not enough space on this disk => do not run testreport.'
  df .
  exit
fi
if [ $checkOut -eq 1 ] ; then
  if test -d $gcmDIR/CVS ; then
    /bin/rm -rf $gcmDIR/verification/??_acesgrid-${sfx}_????????_?
#   ( cd $gcmDIR/verification ; ../tools/do_tst_2+2 -clean )
    echo "cvs update of dir $gcmDIR :"
    ( cd $gcmDIR ; cvs -q -d :pserver:cvsanon@mitgcm.org:/u/gcmpack update -P -d ) 2>&1
    RETVAL=$?
    if test "x$RETVAL" != x0 ; then
       echo "cvs update fail (return val=$RETVAL) => exit"
       exit
    fi
  else
    echo "no dir: $gcmDIR/CVS => try a fresh check-out"
    checkOut=2
  fi
fi
if [ $checkOut -eq 2 ] ; then
  if test -e $gcmDIR ; then
     rm -rf $gcmDIR
  fi
# cvs co MITgcm
  cvs -d :pserver:cvsanon@mitgcm.org:/u/gcmpack co -P -d $gcmDIR MITgcm > /dev/null 2>&1
  /usr/bin/find $gcmDIR -type d | xargs chmod g+rxs
  /usr/bin/find $gcmDIR -type f | xargs chmod g+r
fi

#- change dir to $gcmDIR/verification dir:
if test -e $gcmDIR/verification ; then
  if [ $checkOut -lt 2 ] ; then
    echo " dir $gcmDIR/verification exist" ; fi
  cd $gcmDIR/verification
else
  echo "no dir: $gcmDIR/verification => exit"
  exit
fi

echo ./testreport $options -of $OPTFILE -odir acesgrid-$sfx
./testreport $options -of $OPTFILE -odir acesgrid-$sfx

#echo ''
#echo ../tools/do_tst_2+2 -o acesgrid-$sfx -a NONE
#../tools/do_tst_2+2 -o acesgrid-$sfx -a NONE

