#!/bin/bash
#
#PBS -q one
#PBS -N tst_gnu
#PBS -l nodes=1:ppn=6
#PBS -e /mit/jm_c/test_acesgrid/output/tst_gnu.stderr
#PBS -o /mit/jm_c/test_acesgrid/output/tst_gnu.stdout

# $Header: /u/gcmpack/MITgcm/tools/example_scripts/ACESgrid/Attic/test_aces_gnu_mpi,v 1.7 2012/03/23 21:09:55 jmc Exp $
# $Name:  $

if test -f /etc/profile.d/modules.sh ; then
    . /etc/profile.d/modules.sh
fi
# Note: added "ulimit -s unlimited" in file "~/.bashrc"
# to pass big test (the 2 fizhi-cs-* test & adjoint tests) with MPI

dNam='acesgrid'
TST_DIR="$HOME/test_$dNam"
echo "start from TST_DIR='$TST_DIR' at: "`date`

umask 0022
#- to get case insensitive "ls" (and order of tested experiments)
export LC_ALL="en_US.UTF-8"

HERE=$TST_DIR/output
sfx='gnu'
 module add gcc
 module add openmpi
 OPTFILE="../tools/build_options/linux_amd64_gfortran"
#options="-j 2 -MPI 6 -mf $PBS_NODEFILE"
#EXE="mpirun -machinefile TR_MFILE -v -np TR_NPROC ./mitgcmuv"
 options="-j 2 -MPI 6"
 EXE="mpirun -v -np TR_NPROC ./mitgcmuv"

dAlt=`date +%d` ; dAlt=`expr $dAlt % 3`
if [ $dAlt -eq 1 ] ; then options="$options -fast" ; fi

#- keep a copy of MPI_MFILE:
cp -p $PBS_NODEFILE $HERE"/mf_"$sfx

checkOut=1
#options="$options -nc" ; checkOut=0
#options="$options -q"  ; checkOut=0

gcmDIR="MITgcm_$sfx"
cd $TST_DIR
#- check for disk space:
dsp=`df -P . | tail -1 | awk '{print $5}' | sed 's/%$//'`
if [ $dsp -gt 99 ] ; then
  echo 'Not enough space on this disk => do not run testreport.'
  df .
  exit
fi
if [ $checkOut -eq 1 ] ; then
  if test -d $gcmDIR/CVS ; then
    /bin/rm -rf $gcmDIR/verification/??_${dNam}-${sfx}_????????_?
#   ( cd $gcmDIR/verification ; ../tools/do_tst_2+2 -clean )
    echo "cvs update of dir $gcmDIR :"
    ( cd $gcmDIR ; cvs -q -d :pserver:cvsanon@mitgcm.org:/u/gcmpack update -P -d ) 2>&1
    RETVAL=$?
    if test "x$RETVAL" != x0 ; then
       echo "cvs update on '"`hostname`"' fail (return val=$RETVAL) => exit"
       exit
    fi
  else
    echo "no dir: $gcmDIR/CVS => try a fresh check-out"
    checkOut=2
  fi
fi
if [ $checkOut -eq 2 ] ; then
  if test -e $gcmDIR ; then
     rm -rf $gcmDIR
  fi
# cvs co MITgcm
  cvs -d :pserver:cvsanon@mitgcm.org:/u/gcmpack co -P -d $gcmDIR MITgcm > /dev/null 2>&1
  /usr/bin/find $gcmDIR -type d | xargs chmod g+rxs
  /usr/bin/find $gcmDIR -type f | xargs chmod g+r
fi

#- change dir to $gcmDIR/verification dir:
if test -e $gcmDIR/verification ; then
  if [ $checkOut -lt 2 ] ; then
    echo " dir $gcmDIR/verification exist" ; fi
  cd $gcmDIR/verification
else
  echo "no dir: $gcmDIR/verification => exit"
  exit
fi

# fizhi-cs-32 & aqualev will not compile because of option "-r8" (genmake_local)
echo ./testreport $options -of $OPTFILE -command \"$EXE\" -odir ${dNam}-$sfx \
 -skd 'fizhi-cs-32x32x40 fizhi-cs-aqualev20'
./testreport $options -of $OPTFILE -command "$EXE" -odir ${dNam}-$sfx \
 -skd 'fizhi-cs-32x32x40 fizhi-cs-aqualev20'

