#!/bin/bash
#
#PBS -q one
#PBS -N tst_mp2
#PBS -l nodes=1:ppn=6
#PBS -e /data/jm_c/test_acesgrid/output/tst_mp2.stderr
#PBS -o /data/jm_c/test_acesgrid/output/tst_mp2.stdout

# $Header: /u/gcmpack/MITgcm/tools/example_scripts/ACESgrid/Attic/test_aces_gnu_mp2,v 1.11 2013/01/25 03:57:36 jmc Exp $
# $Name:  $

if test -f /etc/profile.d/modules.sh ; then
    . /etc/profile.d/modules.sh
fi
# Note: added "ulimit -s unlimited" in file "~/.tcshrc"
# to pass big test (the 2 fizhi-cs-* test & adjoint tests) with MPI

dNam='acesgrid'
TST_DIR="/data/jm_c/test_$dNam"
echo "start from TST_DIR='$TST_DIR' at: "`date`

umask 0022
#- to get case insensitive "ls" (and order of tested experiments)
export LC_ALL="en_US.UTF-8"

HERE=$TST_DIR/output
sfx='mp2'
 module add torque
 module add gcc
 module add mvapich2
 OPTFILE="../tools/build_options/linux_amd64_gfortran"
#options="-j 2 -MPI 6 -mf $PBS_NODEFILE"
#EXE="mpirun -machinefile TR_MFILE -v -np TR_NPROC ./mitgcmuv"
 options="-j 2 -MPI 3 -mth"
 EXE="mpirun -v -np TR_NPROC ./mitgcmuv"
#- note: with mpich1, need to set these 2 vars in .tcshrc
 export OMP_NUM_THREADS=2
 export GOMP_STACKSIZE=400m

dAlt=`date +%d` ; dAlt=`expr $dAlt % 3`
if [ $dAlt -eq 1 ] ; then options="$options -fast" ; fi

#- keep a copy of MPI_MFILE:
cp -p $PBS_NODEFILE $HERE"/mf_"$sfx

checkOut=1
#options="$options -nc" ; checkOut=0
#options="$options -q"  ; checkOut=0

gcmDIR="MITgcm_$sfx"
cd $TST_DIR
#- check for disk space:
dsp=`df -P . | tail -1 | awk '{print $5}' | sed 's/%$//'`
if [ $dsp -gt 99 ] ; then
  echo 'Not enough space on this disk => do not run testreport.'
  df .
  exit
fi
if [ $checkOut -eq 1 ] ; then
  if test -d $gcmDIR/CVS ; then
#- remove previous output tar files and tar & remove previous output-dir
    /bin/rm -f $gcmDIR/verification/??_${dNam}-${sfx}_????????_?.tar.gz
    ( cd $gcmDIR/verification
      listD=`ls -1 -d ??_${dNam}-${sfx}_????????_? 2> /dev/null`
      for dd in $listD
      do
        if test -d $dd ; then
          tar -cf ${dd}".tar" $dd > /dev/null 2>&1 && gzip ${dd}".tar" && /bin/rm -rf $dd
          RETVAL=$?
          if test "x$RETVAL" != x0 ; then
             echo "ERROR in tar+gzip prev outp-dir: $dd"
             echo " on '"`hostname`"' (return val=$RETVAL) but continue"
          fi
        fi
      done )
    ( cd $gcmDIR/verification ; ../tools/do_tst_2+2 -clean )
    echo "cvs update of dir $gcmDIR :"
    ( cd $gcmDIR ; cvs -q -d :pserver:cvsanon@mitgcm.org:/u/gcmpack update -P -d ) 2>&1
    RETVAL=$?
    if test "x$RETVAL" != x0 ; then
       echo "cvs update on '"`hostname`"' fail (return val=$RETVAL) => exit"
       exit
    fi
  else
    echo "no dir: $gcmDIR/CVS => try a fresh check-out"
    checkOut=2
  fi
fi
if [ $checkOut -eq 2 ] ; then
  if test -e $gcmDIR ; then
     rm -rf $gcmDIR
  fi
# cvs co MITgcm
  cvs -d :pserver:cvsanon@mitgcm.org:/u/gcmpack co -P -d $gcmDIR MITgcm > /dev/null 2>&1
  /usr/bin/find $gcmDIR -type d | xargs chmod g+rxs
  /usr/bin/find $gcmDIR -type f | xargs chmod g+r
fi

#- change dir to $gcmDIR/verification dir:
if test -e $gcmDIR/verification ; then
  if [ $checkOut -lt 2 ] ; then
    echo " dir $gcmDIR/verification exist" ; fi
  cd $gcmDIR/verification
else
  echo "no dir: $gcmDIR/verification => exit"
  exit
fi

#-- in case 1 proc get stuck, run this script in background to check
check_sh=check_aces_$sfx
if test -x $HERE/$check_sh ; then
   echo "start $check_sh in background"
   mv -f $HERE/${check_sh}.log $HERE/${check_sh}.log_bak
   ( cd $HERE ; ./$check_sh > ${check_sh}.log 2>&1 ) &
fi

# avoid hanging in fizhi-cs-32x32x40 (due to I/O problems with g77)
echo ./testreport $options -of $OPTFILE -command \"$EXE\" -odir ${dNam}-$sfx
./testreport $options -of $OPTFILE -command "$EXE" -odir ${dNam}-$sfx

echo ''
echo ../tools/do_tst_2+2 -mpi -exe \"$EXE\" -o ${dNam}-$sfx -a NONE
../tools/do_tst_2+2 -mpi -exe "$EXE" -o ${dNam}-$sfx -a NONE

