#! /usr/bin/env bash

#- in order to save disc space, take *.bin files from this dir:
fromDir="../input"

fileList=`( cd $fromDir ; ls bathy.box icetopo.exp1 phi0surf.exp1.jmd95z )`

#echo 'fileList=' $fileList

#- and do a symbolic link in the current directory
#   (if the file does not already exist)
if test -d $fromDir ; then
  lnkList='files:'
  for xx in $fileList
  do
    if test -r ${fromDir}/$xx ; then
      if test ! -r $xx ; then
        lnkList=${lnkList}" "$xx
        ln -sf ${fromDir}/$xx .
      fi
    fi
  done
  echo ' link' $lnkList "from dir:" $fromDir
else
  echo " Error:" $fromDir "not a directory"
fi

#- an take pickup files from this dir:
fromDir="../input_ad"

fileList=`( cd $fromDir ; ls pickup* ones_64b.bin )`

#echo 'fileList=' $fileList

#- and do a symbolic link in the current directory
#   (if the file does not already exist)
if test -d $fromDir ; then
  lnkList='files:'
  for xx in $fileList
  do
    if test -r ${fromDir}/$xx ; then
      if test ! -r $xx ; then
        lnkList=${lnkList}" "$xx
        ln -sf ${fromDir}/$xx .
      fi
    fi
  done
  echo ' link' $lnkList "from dir:" $fromDir
else
  echo " Error:" $fromDir "not a directory"
fi
