#! /usr/bin/env bash

#- in order to save disc space, take some files 
#- from this dir:
fromDir="../input"

fileList=`( cd $fromDir ; ls bathy.box eedata* gendata.m ice* p* )`

#echo 'fileList=' $fileList

#- and do a symbolic link in the current directory
#   (if the file does not already exist)
if test -d $fromDir ; then
  lnkList='files:'
  for xx in $fileList
  do
    if test -r ${fromDir}/$xx ; then
      if test ! -r $xx ; then
        lnkList=${lnkList}" "$xx
        ln -sf ${fromDir}/$xx .
      fi
    fi
  done
  echo ' link' $lnkList "from dir:" $fromDir
else
  echo " Error:" $fromDir "not a directory"
fi

fromDir="../input_ad"

fileList=`( cd $fromDir ; ls data genweights.py ones_64b.bin pickup* )`

#echo 'fileList=' $fileList

#- and do a symbolic link in the current directory
#   (if the file does not already exist)
if test -d $fromDir ; then
  lnkList='files:'
  for xx in $fileList
  do
    if test -r ${fromDir}/$xx ; then
      if test ! -r $xx ; then
        lnkList=${lnkList}" "$xx
        ln -sf ${fromDir}/$xx .
      fi
    fi
  done
  echo ' link' $lnkList "from dir:" $fromDir
else
  echo " Error:" $fromDir "not a directory"
fi

# to save disk space, generate obs_melt.bin
# by concatenating six copies of obs_melt_onetimerec.bin 
xx='obs_melt_onetimerec.bin'
xxout='obs_melt.bin'
if test -r $xx ; then
  if test ! -r $xxout ; then
    cat $xx $xx $xx $xx $xx $xx > $xxout
  fi
fi


