#!/bin/bash

# $Header: /u/gcmpack/MITgcm/tools/build_options/unsupported/darwin_g77,v 1.1 2004/08/29 15:38:33 edhill Exp $
#
# tested on G4-PowerBook, 1GHz
# cc-compiler is available only with the Apple Developer Tools, 
# so make sure that those are installed 
# g77 can be optained from FINK: http://fink.sourceforge.net
#

CPP='/usr/bin/cpp -traditional -P'
FC=g77
LINK=g77
FFLAGS='-Wimplicit -Wunused -Wuninitialized'
FOPTIM='-O3 -funroll-loops'
#FOPTIM='-O3 -malign-power -funroll-loops'
NOOPTFLAGS='-O0'

S64='$(TOOLSDIR)/set64bitConst.sh'
#MAKEDEPEND='${TOOLSDIR}/xmakedepend'
MAKEDEPEND=makedepend
DEFINES='-DWORDLENGTH=4'
