#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/unsupported/hp-ux,v 1.1 2010/02/18 17:03:10 jmc Exp $
#

S64='$(TOOLSDIR)/set64bitConst.sh'
MAKEDEPEND=makedepend
DEFINES='-DWORDLENGTH=4'


CPP='/usr/ccs/lbin/cpp -P'
FOPTIM='+O2'
NOOPTFLAGS='+O0'
