#!/bin/bash
#
# $Header: /u/gcmpack/MITgcm/tools/build_options/unsupported/irix64_ip27_f77,v 1.1 2017/06/29 00:09:43 jmc Exp $
# $Name:  $

FC='f77'

S64='$(TOOLSDIR)/set64bitConst.sh'
DEFINES='-DTARGET_SGI -DWORDLENGTH=4'
CPP='/lib/cpp -P -traditional'
EXTENDED_SRC_FLAG='-extend_source'

FFLAGS="$FFLAGS -n32 -bytereclen"
FOPTIM='-O3 -OPT:Olimit=0:roundoff=3:div_split=ON:alias=typed'

INCLUDEDIRS='/usr/include'
LIBS='-lmpi -lscs'
