#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/unsupported/irix,v 1.1 2010/02/18 17:03:11 jmc Exp $
#

S64='$(TOOLSDIR)/set64bitConst.sh'
MAKEDEPEND=makedepend
DEFINES='-DWORDLENGTH=4'


FFLAGS='-extend_source -bytereclen -r10000 -mips4'
FOPTIM='-O2'
NOOPTFLAGS='-O0'
