#!/bin/bash
#
S64='$(TOOLSDIR)/set64bitConst.sh'
MAKEDEPEND=makedepend
CPP='/lib/cpp -P -traditional'

DEFINES='-DALLOW_USE_MPI -DALWAYS_USE_MPI -DTARGET_SGI -DWORDLENGTH=4'
FC='f77'
FFLAGS='-n32 -extend_source -bytereclen'
FOPTIM='-O3 -OPT:Olimit=0:roundoff=3:div_split=ON:alias=typed'
LIBS='-lmpi -lscs'
INCLUDEDIRS='/usr/include'
