#!/bin/bash
#
# $Header: /u/gcmpack/MITgcm/tools/build_options/unsupported/irix64_ip35+mpi_gfdl,v 1.1 2011/09/29 16:07:05 jmc Exp $
# $Name:  $

S64='$(TOOLSDIR)/set64bitConst.sh'
MAKEDEPEND=makedepend
CPP='/lib/cpp -P'
DEFINES='-DTARGET_SGI -DWORDLENGTH=4 -DALLOW_USE_MPI -DALWAYS_USE_MPI'
FC='f77'
FFLAGS='-extend_source -mp -mpio -bytereclen -mips4 -r8 -static'
FOPTIM='-O3'
LIBS='-L/opt/mpt/1510/usr/lib64 -lmpi'
INCLUDEDIRS='/opt/mpt/1510/usr/include'
