#!/bin/bash
#
# $Header: /u/gcmpack/MITgcm/tools/build_options/unsupported/irix64_ip27_f77+mpi,v 1.1 2011/09/29 16:06:12 jmc Exp $
# $Name:  $

S64='$(TOOLSDIR)/set64bitConst.sh'
MAKEDEPEND=makedepend
CPP='/lib/cpp -P -traditional'

DEFINES='-DALLOW_USE_MPI -DALWAYS_USE_MPI -DTARGET_SGI -DWORDLENGTH=4'
FC='f77'
FFLAGS='-n32 -extend_source -bytereclen'
FOPTIM='-O3 -OPT:Olimit=0:roundoff=3:div_split=ON:alias=typed'
LIBS='-lmpi -lscs'
INCLUDEDIRS='/usr/include'
