#!/bin/bash

S64='$(TOOLSDIR)/set64bitConst.sh'
%MAKEDEPEND=makedepend
CPP='/lib/cpp -P -traditional'

DEFINES='-DTARGET_SGI -DWORDLENGTH=4'
FC='f77'
FC_NAMEMANGLE='#define FC_NAMEMANGLE(X) X ## _'
FFLAGS='-n32 -extend_source -bytereclen'
FOPTIM='-O3 -OPT:Olimit=0:roundoff=3:div_split=ON:alias=typed'
LIBS='-lmpi'
INCLUDEDIRS='/usr/include'

