#!/bin/bash
#
#

S64='$(TOOLSDIR)/set64bitConst.sh'
MAKEDEPEND=makedepend
DEFINES='-DWORDLENGTH=4'


INCLUDES='-I/usr/include'
FFLAGS='-extend_source -bytereclen -r10000 -64'
FOPTIM='-O2'
NOOPTFLAGS='-O0'
LIBS='-lmpi'
