#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/unsupported/linux_ia32_pgf77+authors_fc2,v 1.1 2010/03/21 16:08:29 jmc Exp $
#

FC='/usr/local/pkg/pgi/pgi-5.2/linux86/5.2/bin/pgf77'
CC='/usr/local/pkg/pgi/pgi-5.2/linux86/5.2/bin/pgcc'
DEFINES='-DWORDLENGTH=4'
CPP='cpp -traditional -P'

if test "x$IEEE" = x ; then
    #  No need for IEEE-754
    FFLAGS='-byteswapio -r8 -Mnodclchk -Mextend'
    FOPTIM='-fastsse -Mvect=cachesize:524288,transform'
else
    #  Try to follow IEEE-754
    FFLAGS='-byteswapio -r8 -Mnodclchk -Mextend'
    FOPTIM='-O0 -Mvect=sse -Mscalarsse -Mcache_align -Mnoflushz -Kieee'
fi

