#!/bin/bash
#
#


FC='/usr/local/pkg/mpi/mpi-1.2.4..8a-gm-1.5/g77/bin/mpif77'
CC='/usr/local/pkg/mpi/mpi-1.2.4..8a-gm-1.5/g77/bin/mpicc'
DEFINES='-DALLOW_USE_MPI -DALWAYS_USE_MPI -D_BYTESWAPIO -DWORDLENGTH=4'
INCLUDEDIRS='/usr/local/pkg/mpi/mpi-1.2.4..8a-gm-1.5/g77/include'
INCLUDES='-I/usr/local/pkg/mpi/mpi-1.2.4..8a-gm-1.5/g77/include'
CPP='/lib/cpp  -traditional -P'
NOOPTFLAGS='-O0'

if test "x$IEEE" = x ; then
    #  No need for IEEE-754
    FFLAGS='-Wimplicit -Wunused -Wuninitialized'
    FOPTIM='-O3 -malign-double -funroll-loops'
else
    #  Try to follow IEEE-754
    FFLAGS='-Wimplicit -Wunused -ffloat-store'
    FOPTIM='-O0 -malign-double'
fi

# netcdf
#LIBS="-lnetcdf"

