#!/bin/bash
#
# $Header: /u/gcmpack/MITgcm/tools/build_options/unsupported/linux_ppc64_xlf_bigred+mth,v 1.1 2011/09/29 16:21:44 jmc Exp $
# $Name:  $

#  tested on Big Red, ce107 Aug 30 2007
#  using the following invocation:
#    ../../../tools/genmake2 -mods=../code -of=../../../tools/build_options/linux_ppc64_xlf_bigred+mth


S64='$(TOOLSDIR)/set64bitConst.sh'
MAKEDEPEND=makedepend
DEFINES='-DWORDLENGTH=4 -DNML_TERMINATOR -DUSE_OMP_THREADING'
INCLUDES='-I/N/soft/linux-sles9-ppc64/netcdf-3.6.1-ibm-64/include'
CPP='/lib/cpp -traditional -P'
FC='xlf_r -q64'
CC='xlc_r -q64'
LINK='xlf_r -q64'
LIBS='-L/N/soft/linux-sles9-ppc64/netcdf-3.6.1-ibm-64/lib -lnetcdf'
FFLAGS='-qfixed=132'
if test "x$IEEE" = x ; then
    #  No need for IEEE-754
FOPTIM='-O5 -qsmp=omp -qarch=auto -qtune=auto -qcache=auto -qmaxmem=-1 -qipa=noobject:partition=large:threads'
CFLAGS='-O5 -qsmp=omp -qinlglue -qarch=auto -qtune=auto -qcache=auto -qmaxmem=-1 -qipa=noobject:partition=large:threads'
else
FOPTIM='-O3 -qsmp=omp -qstrict -qarch=auto -qtune=auto -qcache=auto -qmaxmem=-1'
CFLAGS='-O3 -qsmp=omp -qstrict -qarch=auto -qtune=auto -qcache=auto -qmaxmem=-1'
fi
FC_NAMEMANGLE="#define FC_NAMEMANGLE(X) X"
