#!/bin/bash
#
# These are the build options used with the Intel compiler together with OpenAD and MPI

CC='mpicc'
FC='mpif77'
F90C='mpif90'
LINK='mpif90'

DEFINES='-DALLOW_USE_MPI -DALWAYS_USE_MPI -DWORDLENGTH=4'
CPP='cpp -traditional -P'
F90FIXEDFORMAT='-fixed -Tf'

NOOPTFLAGS='-O0'
NOOPTFILES='mds_byteswapr8.F mds_byteswapr4.F mds_byteswapi4.F'

FFLAGS="$FFLAGS -132 -w95 -W0 -WB -convert big_endian -assume byterecl"
if test "x$IEEE" = x ; then
    FOPTIM='-O3 -align'
else
    FOPTIM='-O0 -g -noalign'
    FFLAGS="$FFLAGS -xW -pc64"
fi

NOOPTFILES=$NOOPTFILES' mitcplr_char2real.F mitcplr_real2char.F'
NOOPTFILES=$NOOPTFILES' mitcplr_char2int.F mitcplr_int2char.F mds_byteswap.F'

F90FLAGS=$FFLAGS
F90OPTIM=$FOPTIM

INCLUDES='-I${MPIROOT}/include'
LIBS=''
