#!/bin/bash
#
# $Header: /u/gcmpack/MITgcm/tools/build_options/unsupported/linux_ia32_pgf77+mpi,v 1.1 2011/09/29 16:17:14 jmc Exp $
# $Name:  $

FC='pgf77'

DEFINES='-DWORDLENGTH=4 -DNML_EXTENDED_F77'
#CPP='cpp -traditional -P'
EXTENDED_SRC_FLAG='-Mextend'
GET_FC_VERSION="-V"

INCLUDES='-I/usr/local/mpich-1.2.1/pgi_fortran_binding/include'
LIBS='-L/usr/local/mpich-1.2.1/pgi_fortran_binding/lib/ -lfmpich -lmpich'
#INCLUDES='-I/usr/local/mpich-1.2.1/pgi_fortran_binding/include'
INCLUDES='$INCLUDES -I/usr/local/include'

#LIBS='-L/usr/local/mpich-1.2.1/pgi_fortran_binding/lib/ -lfmpich -lmpich'
LIBS='-L/usr/local/lib/LINUX/ch_p4/ -lfmpich -lmpich'

if test "x$IEEE" = x ; then
    #  No need for IEEE-754
    FFLAGS="$FFLAGS -byteswapio -Mnodclchk"
    FOPTIM='-tp p6 -v -O2 -Munroll'
# -Mvect=cachesize:512000,transform
else
    #  Try to follow IEEE-754
    FFLAGS="$FFLAGS -byteswapio"
    FOPTIM='-tp p6 -v -O0 -Munroll -Kieee'
# -Mvect=cachesize:512000,transform
fi
#- might want to use '-r8' for fizhi pkg:
#FFLAGS="$FFLAGS -r8"

