#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/unsupported/linux_ia32_ifc+mpi_cg01,v 1.1 2009/07/21 20:00:18 jmc Exp $
#  $Name:  $
#

FC='/usr/local/pkg/mpi/mpi-1.2.4..8a-gm-1.5/intel/bin/mpif77'
LINK='/usr/local/pkg/mpi/mpi-1.2.4..8a-gm-1.5/intel/bin/mpif77'
INCLUDEDIRS='/usr/local/pkg/mpi/mpi-1.2.4..8a-gm-1.5/intel/include'
INCLUDES='-I/usr/local/pkg/mpi/mpi-1.2.4..8a-gm-1.5/intel/include'
DEFINES='-DALLOW_USE_MPI -DALWAYS_USE_MPI -D_BYTESWAPIO -DWORDLENGTH=4'
CPP='/lib/cpp  -traditional -P'
LIBS='-lPEPCF90'

NOOPTFLAGS='-O0'
NOOPTFILES='mds_byteswapr8.F mds_byteswapr4.F mds_byteswapi4.F'

#  Note that the -mp switch is for ieee "maintain precision" and is
#  roughly equivalent to -ieee
if test "x$IEEE" = x ; then
    FOPTIM='-O3 -align'
#P3 FOPTIM=$FOPTIM' -tpp6 -xWKM'
#P4 FOPTIM=$FOPTIM' -tpp7 -xWKM'
    FFLAGS='-132 -r8 -i4 -w95 -W0 -WB'
else
    FOPTIM='-O0 -noalign -CA -CB -CU -CV -CS'
#   FFLAGS='-mp -132 -r8 -i4 -w95 -W0 -WB'
    FFLAGS='-132 -r8 -i4 -w95 -W0 -WB -pc64 -xW'
fi

NOOPTFILES=$NOOPTFILES' mitcplr_char2real.F mitcplr_real2char.F'
NOOPTFILES=$NOOPTFILES' mitcplr_char2int.F mitcplr_int2char.F mds_byteswap.F'

