#!/bin/bash
#
#
# Build options for Fedore Core 3 x86-64 Opteron with the Fedore LAM version
# tested on (Linux batsi 2.6.10-1.766_FC3smp #1 SMP Wed Feb 9 23:17:48 EST 2005 x86_64 x86_64 x86_64 GNU/Linux) system 20051802
#

CC=pathcc
FC=pathf90
# We need to link statically to avoid the annoying _rtld_global_ro@GLIBC_PRIVATE
# error message during linking
LINK='pathf90 -static'
# We need to add the LAM (gcc/g++/g77 compiled) libraries
LIBS='-L/usr/lib64 -llammpio -llamf77mpi -lmpi -llam -lutil -lpthread -lm'
# We need to add -DTARGET_LAM as older versions of LAM did not know
# about MPI_REAL8 etc.
DEFINES='-DTARGET_LAM -D_BYTESWAPIO -DWORDLENGTH=4 -DALLOW_USE_MPI -DALWAYS_USE_MPI'
CPP='cpp -traditional -P'
NOOPTFLAGS='-O0'
MAKEDEPEND=/usr/X11R6/bin/makedepend
INCLUDES=-I/usr/include
FFLAGS='-r8 -extend_source'
if test "x$IEEE" = x ; then
    #  No need for IEEE-754
    FOPTIM='-Ofast -LNO:fusion=2'
else
    #  Try to follow IEEE-754
    FOPTIM='-Ofast -LNO:fusion=2 -OPT:roundoff=0:IEEE_arithmetic=1'
fi

