#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/unsupported/osf1_halem,v 1.1 2010/02/18 17:03:11 jmc Exp $
#

#  confirmed on Halem by eh3, 2003-09-03

S64='$(TOOLSDIR)/set64bitConst.sh'
MAKEDEPEND='mkdep -f depend.out'
DEFINES='-DTARGET_DEC -DWORDLENGTH=1'


CPP='/usr/local/bin/cpp -P -traditional'
#ph: makedepend not available on some/many DEC Alpha's; use mkdep instead
FC='f77'
LINK='f77'
FFLAGS='-convert big_endian -r8 -extend_source -automatic -call_shared -notransform_loops -align dcommons'
FOPTIM='-O5 -fast -tune host -inline all'
#ph: -O5 probably too aggressive in conjunction with adjoint code
NOOPTFILES='barrier.F different_multiple.F external_fields_load.F'
NOOPTFLAGS='-O0'
RMFILES='*.p.out'
