#!/bin/bash
#
#

S64='$(TOOLSDIR)/set64bitConst.sh'
MAKEDEPEND=makedepend
DEFINES='-DWORDLENGTH=4'


#ph: e.g. halem.gsfc.nasa.gov
LIBS='-lfmpi -lmpi -lkmp_osfp10 -pthread'
#ph: -lkmp_osfp10 not needed on some/many platforms
