#!/bin/bash
#
#

S64='$(TOOLSDIR)/set64bitConst.sh'
MAKEDEPEND=makedepend
DEFINES='-DALLOW_USE_MPI -DALWAYS_USE_MPI -DTARGET_AIX -DWORDLENGTH=4'

# tested on blackforest, IBM SP3 at NCAR 10/2004 
INCLUDES='-I/usr/lpp/ppe.poe/include'
CPP='/lib/cpp -P'
FC='mpxlf95'
LINK='mpxlf95'
LIBS='-L/usr/local/apps/mass -lmass'
FFLAGS='-qfixed=132 -bmaxdata:0x80000000'
FOPTIM='-O3 -qarch=pwr3 -qtune=pwr3 -qcache=auto -qmaxmem=-1'
FC_NAMEMANGLE="#define FC_NAMEMANGLE(X) X"
