#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/build_options/unsupported/sp3+mpi,v 1.1 2010/02/18 17:03:11 jmc Exp $
#

#  tested on blackforest, ce107 Jan 2005


S64='$(TOOLSDIR)/set64bitConst.sh'
MAKEDEPEND=makedepend
DEFINES='-DALLOW_USE_MPI -DALWAYS_USE_MPI -DTARGET_AIX -DWORDLENGTH=4'

INCLUDES='-I/usr/lpp/ppe.poe/include'
CPP='/lib/cpp -P'
CC='mpcc_r -q64'
FC='mpxlf95 -q64'
LINK='mpxlf95_r -q64'
LIBS='-L/usr/local/apps/mass -lmass'
FFLAGS='-qfixed=132' 
FOPTIM='-O3 -qarch=pwr3 -qtune=pwr3 -qcache=auto -qmaxmem=-1'
FC_NAMEMANGLE="#define FC_NAMEMANGLE(X) X"
