#!/bin/bash
#
# $Header: /u/gcmpack/MITgcm/tools/build_options/unsupported/sp4+mpi,v 1.1 2011/09/29 16:25:02 jmc Exp $
# $Name:  $

#  tested on bluesky, ce107 Dec 2005
#  using the following invocation:
#    ../../../tools/genmake2 -mods=../code -of=../../../tools/build_options/sp4 -make=gmake

S64='$(TOOLSDIR)/set64bitConst.sh'
MAKEDEPEND=makedepend
DEFINES='-DALLOW_USE_MPI -DALWAYS_USE_MPI -DTARGET_AIX -DWORDLENGTH=4'

INCLUDES='-I/usr/lpp/ppe.poe/include/thread64 -I/usr/local/include'
CPP='/lib/cpp -P'
CC='mpcc_r -q64'
FC='mpxlf95_r -q64'
LINK='mpxlf95_r -q64'
LIBS='-L/usr/local/apps/mass -lmass -L/usr/local/lib64/r4i4'
FFLAGS='-qfixed=132'
if test "x$IEEE" = x ; then
    #  No need for IEEE-754
    FOPTIM='-O3 -Q -qarch=pwr4 -qtune=pwr4 -qcache=auto -qmaxmem=-1'
    CFLAGS='-O3 -Q -qarch=pwr4 -qtune=pwr4 -qcache=auto -qmaxmem=-1'
else
    #  Try to follow IEEE-754
    FOPTIM='-O3 -qstrict -Q -qarch=pwr4 -qtune=pwr4 -qcache=auto -qmaxmem=-1'
    CFLAGS='-O3 -qstrict -Q -qarch=pwr4 -qtune=pwr4 -qcache=auto -qmaxmem=-1'
fi
FC_NAMEMANGLE="#define FC_NAMEMANGLE(X) X"
