#!/bin/bash
#
# $Header: /u/gcmpack/MITgcm/tools/build_options/unsupported/sp4-32bit,v 1.1 2011/09/29 16:24:31 jmc Exp $
# $Name:  $

#  tested on bluesky, ce107 Jan 2005

S64='$(TOOLSDIR)/set64bitConst.sh'
MAKEDEPEND=makedepend
DEFINES='-DTARGET_AIX -DWORDLENGTH=4'
INCLUDES='-I/usr/local/include'

CPP='/lib/cpp -P'
CC='cc_r'
FC='xlf95_r'
LINK='xlf95_r'
LIBS='-L/usr/local/apps/mass -lmass -L/usr/local/lib32/r4i4'
FFLAGS='-qfixed=132 -bmaxdata:0x80000000'
if test "x$IEEE" = x ; then
    #  No need for IEEE-754
    FOPTIM='-O3 -Q -qarch=pwr4 -qtune=pwr4 -qcache=auto -qmaxmem=-1'
    CFLAGS='-O3 -Q -qarch=pwr4 -qtune=pwr4 -qcache=auto -qmaxmem=-1'
else
    #  Try to follow IEEE-754
    FOPTIM='-O3 -qstrict -Q -qarch=pwr4 -qtune=pwr4 -qcache=auto -qmaxmem=-1'
    CFLAGS='-O3 -qstrict -Q -qarch=pwr4 -qtune=pwr4 -qcache=auto -qmaxmem=-1'
fi
FC_NAMEMANGLE="#define FC_NAMEMANGLE(X) X"
HPMTINC='-I/usr/local/hpmtoolkit/include'
HPMTLIB='-L/usr/local/hpmtoolkit/lib -lhpm_r -lpmapi'
GSLINC='-I/home/bluesky/evangeli/gsl-1.5/include'
GSLLIB='-L/home/bluesky/evangeli/gsl-1.5/lib -lgsl -lgslcblas'
PAPIINC='-I/usr/local/include'
PAPILIB='-L/usr/local/lib -lpapi'
