#!/bin/bash
#
# $Header: /u/gcmpack/MITgcm/tools/build_options/unsupported/sp6+mpi_ncar,v 1.1 2011/09/29 16:24:03 jmc Exp $
# $Name:  $

S64='$(TOOLSDIR)/set64bitConst.sh'
MAKEDEPEND=makedepend

DEFINES='-DALLOW_USE_MPI -DALWAYS_USE_MPI -DTARGET_AIX -DWORDLENGTH=4 -DNML_TERMINATOR'

INCLUDES='-I/usr/lpp/ppe.poe/include/thread64 -I/contrib/netcdf-3.6.2/include'
CPP='/lib/cpp -P'
CC='mpcc_r -q64'
FC='mpxlf_r -q64'
LINK='mpxlf_r -q64'
LIBS='-lmass -L/contrib/netcdf-3.6.2/lib'
FFLAGS='-qfixed=132'
if test "x$IEEE" = x ; then
    #  No need for IEEE-754
    FOPTIM='-O3 -Q -qarch=pwr6 -qtune=pwr6 -qcache=auto -qmaxmem=-1'
    CFLAGS='-O3 -Q -qarch=pwr6 -qtune=pwr6 -qcache=auto -qmaxmem=-1'
else
    #  Try to follow IEEE-754
    FOPTIM='-O3 -qstrict -Q -qarch=pwr6 -qtune=pwr6 -qcache=auto -qmaxmem=-1'
    CFLAGS='-O3 -qstrict -Q -qarch=pwr6 -qtune=pwr6 -qcache=auto -qmaxmem=-1'
fi
FC_NAMEMANGLE="#define FC_NAMEMANGLE(X) X"

MPI_HEADER_FILES='mpif.h'
MPI_HEADER_FILES_INC='./mpi_headers/mpif.h'
MPIINCLUDEDIR='/usr/lpp/ppe.poe/include/thread64'

HPMTINC=''
HPMTLIB='-lhpm_r -lpmapi'
GSLINC='-I/contrib/gsl-1.12/include'
GSLLIB='-L/contrib/gsl-1.12/gsl-1.5/lib64 -lgsl -lgslcblas'
PAPIINC='-I/contrib/papi-3.6.2/include'
PAPILIB='-L/contrib/papi-3.6.2/lib -lpapi -lpmapi'

