#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/adjoint_options/Attic/adjoint_dic,v 1.4 2010/10/01 14:44:34 heimbach Exp $
#  $Name:  $
#

#  This file contains the default settings for the adjoint and 
#  tangent-linear compilers.  If you need to change these settings,
#  please make a separate (local) copy of this file.

# TAMC=/data43/ralf/tamc/tamc
# TAF=~fastopt/bin/taf
# STAF=staf

TAF=staf
TAMC=tamc

AD_TAMC_FLAGS='-reverse -admark ad -i4 -r4 -l tamc_ad.log'
AD_TAF_FLAGS='-v1 -reverse -admark ad -i4 -r4 -l taf_ad.log -flow taf_ad_flow.log'
FTL_TAMC_FLAGS='-forward -ftlmark g_ -i4 -r4 -l tamc_ftl.log'
FTL_TAF_FLAGS='-v1 -forward -ftlmark g_ -i4 -r4 -l taf_ftl.log -flow taf_ftl_flow.log'
SVD_TAMC_FLAGS='-reverse -forward -pure -i4 -r4 -l tamc_svd.log'
SVD_TAF_FLAGS='-v1 -reverse -forward -pure -i4 -r4 -l taf_svd.log -flow taf_flow.log'

DIFF_FLAGS="-toplevel 'the_main_loop'    \
            -input 'xx_dic \
		    xx_gen2d_dummy'       \
            -output 'fc' "

AD_TAMC_FLAGS="$AD_TAMC_FLAGS $DIFF_FLAGS"
AD_TAF_FLAGS="$AD_TAF_FLAGS   $DIFF_FLAGS"

FTL_TAMC_FLAGS="$FTL_TAMC_FLAGS $DIFF_FLAGS"
FTL_TAF_FLAGS="$FTL_TAF_FLAGS   $DIFF_FLAGS"

SVD_TAMC_FLAGS="$SVD_TAMC_FLAGS $DIFF_FLAGS"
SVD_TAF_FLAGS="$SVD_TAF_FLAGS   $DIFF_FLAGS"
