#!/bin/bash
#
#  This AD option-file contains the default settings for the adjoint
#  and tangent-linear compilers.  If you need to change these settings,
#  please make a separate (local) copy of this file.

# TAMC=/data43/ralf/tamc/tamc
# TAF=~fastopt/bin/taf
# STAF=staf

TAF=staf
TAMC=tamc

if test "x$USE_DIVA" = "x1" ; then
    DIVA='true'
    DIVA_FLAG="-pure"
    USE_MPI=1
else
    DIVA_FLAG=
fi

AD_TAMC_FLAGS="-reverse -admark ad -i4 -r4 -l tamc_ad.log $AD_TAMC_FLAGS"
FTL_TAMC_FLAGS="-forward -ftlmark g_ -i4 -r4 -l tamc_ftl.log $FTL_TAMC_FLAGS"
SVD_TAMC_FLAGS="-reverse -forward -pure -i4 -r4 -l tamc_svd.log $SVD_TAMC_FLAGS"
if test "x$TAMC_COMPATIBILITY_MODE" = "x1"
then
    AD_TAMC_FLAGS="-v1 -nonew_arg $AD_TAMC_FLAGS"
    FTL_TAMC_FLAGS="-v1 -nonew_arg $FTL_TAMC_FLAGS"
    SVD_TAMC_FLAGS="-v1 -nonew_arg $SVD_TAMC_FLAGS"
fi

AD_TAF_FLAGS="-reverse $DIVA_FLAG -l taf_ad.log $AD_TAF_FLAGS"
FTL_TAF_FLAGS="-forward -l taf_ftl.log $FTL_TAF_FLAGS"
SVD_TAF_FLAGS="-reverse -forward -pure -l taf_svd.log $SVD_TAF_FLAGS"

TAF_COMMON_FLAGS="-i4 -r4 -intrinsic system,flush"

if test "x$USE_EXTENDED_SRC" = "xt"; then
    TAF_COMMON_FLAGS="-e $TAF_COMMON_FLAGS"
fi

#- after Jan 14, 2016, TAF default is "-f95"
if test "x$ALWAYS_USE_F90" = "x1" ; then
    TAF_COMMON_FLAGS="-f90 $TAF_COMMON_FLAGS"
elif test "x$ALWAYS_USE_F95" = "x1" ; then
    TAF_COMMON_FLAGS="-f95 $TAF_COMMON_FLAGS"
    TAF_COMPILER=-f95
else
    TAF_COMMON_FLAGS="-f77 $TAF_COMMON_FLAGS"
fi

#- switch to fastopt.net TAF server (instead of default fastopt.net):
if test -z "$TAF_SERVER" ; then
    TAF_COMMON_FLAGS="-server fastopt.net $TAF_COMMON_FLAGS"
else
    TAF_COMMON_FLAGS="-server $TAF_SERVER $TAF_COMMON_FLAGS"
fi

#- in case we need to show some MPI code to TAF:
if test "x$USE_MPI" = "x1" -a "x$MPI" != x
then
    MPI_TAF_OPTIONS='-mpi -include $(LOCAL_MPI_HEADERS) -I./mpi_headers'
else
    MPI_TAF_OPTIONS=
fi

if test "x$USE_SVD" = "x1" ; then
    TAF_FC=objf_state_final
    LIBS="${LIBS} -larpack"
else
    TAF_FC=fc
fi
DIFF_FLAGS="-toplevel 'the_main_loop' \
            -input 'xx_obcsn_dummy    \
	            xx_obcss_dummy    \
		    xx_obcsw_dummy    \
		    xx_obcse_dummy    \
                    xx_genarr2d_dummy \
		    xx_genarr3d_dummy \
		    xx_gentim2d_dummy'\
            -output '$TAF_FC'"

AD_TAMC_FLAGS="$AD_TAMC_FLAGS $DIFF_FLAGS"
AD_TAF_FLAGS="$TAF_COMMON_FLAGS $AD_TAF_FLAGS $MPI_TAF_OPTIONS $DIFF_FLAGS"

FTL_TAMC_FLAGS="$FTL_TAMC_FLAGS $DIFF_FLAGS"
FTL_TAF_FLAGS="$TAF_COMMON_FLAGS $FTL_TAF_FLAGS $MPI_TAF_OPTIONS $DIFF_FLAGS"

SVD_TAMC_FLAGS="$SVD_TAMC_FLAGS $DIFF_FLAGS"
SVD_TAF_FLAGS="$TAF_COMMON_FLAGS $SVD_TAF_FLAGS $MPI_TAF_OPTIONS $DIFF_FLAGS"
