#!/bin/bash
#
#  This AD option-file contains the default settings for the adjoint
#  and tangent-linear compilers.  If you need to change these settings,
#  please make a separate (local) copy of this file.

# TAMC=/data43/ralf/tamc/tamc
# TAF=~fastopt/bin/taf
# STAF=staf

TAF=staf
TAMC=tamc

if test "x$USE_DIVA" = "x1" ; then
    DIVA='true'
    DIVA_FLAG="-pure"
else
    DIVA_FLAG=
fi
AD_TAMC_FLAGS="-reverse -admark ad -i4 -r4 -l tamc_ad.log $AD_TAMC_FLAGS"
FTL_TAMC_FLAGS="-forward -ftlmark g_ -i4 -r4 -l tamc_ftl.log $FTL_TAMC_FLAGS"
SVD_TAMC_FLAGS="-reverse -forward -pure -i4 -r4 -l tamc_svd.log $SVD_TAMC_FLAGS"

TAF_COMMON_FLAGS="-i4 -r4 -intrinsic system,flush"
AD_TAF_FLAGS="-reverse $DIVA_FLAG $TAF_COMMON_FLAGS -l taf_ad.log $AD_TAF_FLAGS"
FTL_TAF_FLAGS="-forward $TAF_COMMON_FLAGS -l taf_ftl.log $FTL_TAF_FLAGS"
SVD_TAF_FLAGS="-reverse -forward -pure $TAF_COMMON_FLAGS -l taf_svd.log $SVD_TAF_FLAGS"

#- after Jan 14, 2016, TAF default is "-f95"
if test "x$ALWAYS_USE_F90" = "x1" ; then
    TAF_COMPILER=-f90
elif test "x$ALWAYS_USE_F95" = "x1" ; then
    TAF_COMPILER=-f95
else
    TAF_COMPILER=-f77
fi
AD_TAF_FLAGS="$TAF_COMPILER $AD_TAF_FLAGS"
FTL_TAF_FLAGS="$TAF_COMPILER $FTL_TAF_FLAGS"
SVD_TAF_FLAGS="$TAF_COMPILER $SVD_TAF_FLAGS"

#- switch to fastopt.net TAF server (instead of default fastopt.net):
if test "x$TAF_SERVER" = "x1" ; then
    TAF_USE_SERVER="-server $TAF_SERVER"
else
    TAF_USE_SERVER="-server fastopt.net"
fi
AD_TAF_FLAGS="$TAF_USE_SERVER $AD_TAF_FLAGS"
FTL_TAF_FLAGS="$TAF_USE_SERVER $FTL_TAF_FLAGS"
SVD_TAF_FLAGS="$TAF_USE_SERVER $SVD_TAF_FLAGS"

#- in case we need to show some MPI code to TAF:
if test "x$DIVA" = "xtrue" ; then
    if test "x$MPI" != x ; then
#	MPI_TAF_OPTIONS='-mpi -include $(LOCAL_MPI_HEADERS) -I./mpi_headers'
	MPI_TAF_OPTIONS='-mpi -I./mpi_headers'
	AD_TAF_FLAGS="$AD_TAF_FLAGS $MPI_TAF_OPTIONS"
	FTL_TAF_FLAGS="$FTL_TAF_FLAGS $MPI_TAF_OPTIONS"
	SVD_TAF_FLAGS="$SVD_TAF_FLAGS $MPI_TAF_OPTIONS"
    fi
fi

if test "x$USE_SVD" = "x1" ; then
    TAF_FC=objf_state_final
    LIBS="${LIBS} -larpack"
else
    TAF_FC=fc
fi
DIFF_FLAGS="-toplevel 'the_main_loop' \
            -input 'xx_obcsn_dummy    \
	            xx_obcss_dummy    \
		    xx_obcsw_dummy    \
		    xx_obcse_dummy    \
                    xx_genarr2d_dummy \
		    xx_genarr3d_dummy \
		    xx_gentim2d_dummy'\
            -output '$TAF_FC'"

AD_TAMC_FLAGS="$AD_TAMC_FLAGS $DIFF_FLAGS"
AD_TAF_FLAGS="$AD_TAF_FLAGS   $DIFF_FLAGS"

FTL_TAMC_FLAGS="$FTL_TAMC_FLAGS $DIFF_FLAGS"
FTL_TAF_FLAGS="$FTL_TAF_FLAGS   $DIFF_FLAGS"

SVD_TAMC_FLAGS="$SVD_TAMC_FLAGS $DIFF_FLAGS"
SVD_TAF_FLAGS="$SVD_TAF_FLAGS   $DIFF_FLAGS"
