#!/bin/bash
#
#  $Header: /u/gcmpack/MITgcm/tools/adjoint_options/adjoint_oad,v 1.4 2013/07/07 01:19:22 jmc Exp $
#  $Name:  $
#

#  This file contains settings for OpenAD

export OPENAD=true
# debug defines OAD_DEBUG, OAD_DEBUG_CP, OAD_DEBUG_JOINT, OAD_DEBUG_SPLIT1, OAD_DEBUG_SPLIT2  

#DEFINES="$DEFINES -DOAD_DEBUG -DDEFAULT_R8"
DEFINES="$DEFINES -DDEFAULT_R8"

