#! /bin/sh

#-- Import input files from experiment global_ocean.cs32x15 
#   this reduce the disk space required when downloading this set-up

impDir='../../global_ocean.cs32x15/input'
dirOcn=`pwd`

echo 'Import Input files from dir:' $impDir
echo ''
cd $impDir

listF=`ls *.bin`
for xx in $listF
do
 if test -f $dirOcn/$xx
 then echo 'file' $xx ' already exists'
 else echo ' cp ' $xx
  cp -p -i $xx $dirOcn
 fi 
done

cd $dirOcn
