#! /usr/bin/env bash

#  $Header: /u/gcmpack/MITgcm/verification/cpl_aim+ocn/input_ocn/prepare_run,v 1.2 2009/01/02 01:03:25 jmc Exp $
#  $Name:  $
 
#- in order to save disc space, from this dir:
fromDir="../../global_ocean.cs32x15/input"
#  link files:
fileList=`(cd $fromDir ; ls *.bin)`

#- and do a symbolic link in the current directory 
#   (if the file does not already exist)
if test -d $fromDir ; then
  lnkList='files:'
  for xx in $fileList
  do
    if test -r ${fromDir}/$xx ; then 
      if test ! -r $xx ; then 
        lnkList=${lnkList}" "$xx
        ln -sf ${fromDir}/$xx .
      fi
    fi
  done
  echo ' link' $lnkList "from dir:" $fromDir
else
  echo " Error:" $fromDir "not a directory"
fi
 
#- in order to save disc space, from this dir:
fromDir='../../tutorial_held_suarez_cs/input'
#  link files:
fileList=`(cd $fromDir ; ls *.face00?.bin)`

#- and do a symbolic link in the current directory 
#   (if the file does not already exist)
if test -d $fromDir ; then
  lnkList='files:'
  for xx in $fileList
  do
    if test -r ${fromDir}/$xx ; then 
      if test ! -r $xx ; then 
        lnkList=${lnkList}" "$xx
        ln -sf ${fromDir}/$xx .
      fi
    fi
  done
  echo ' link' $lnkList "from dir:" $fromDir
else
  echo " Error:" $fromDir "not a directory"
fi
echo ''
