#! /bin/sh

#-- Import input files from experiment global_ocean.cs32x15 
#-- Import grid-files from experiment tutorial_held_suarez_cs
#   this reduce the disk space required when downloading this set-up

dirOcn=`pwd`
impDir='../../global_ocean.cs32x15/input'

echo 'Import Input files from dir:' $impDir
cd $impDir

listF=`ls *.bin`
for xx in $listF
do
 if test -f $dirOcn/$xx
 then echo 'file' $xx ' already exists'
 else echo ' cp ' $xx
  cp -p -i $xx $dirOcn
 fi 
done
echo ''

cd $dirOcn

impDir='../../tutorial_held_suarez_cs/input'

echo 'Import Grid-files from dir:' $impDir
cd $impDir

listF=`ls *.face00?.bin`
for xx in $listF
do
 if test -f $dirOcn/$xx
 then echo 'file' $xx ' already exists'
 else echo ' cp ' $xx
  cp -p -i $xx $dirOcn
 fi 
done
echo ''

cd $dirOcn
