C $Header:

#ifdef ALLOW_SEAICE

C     /==========================================================\
C     | SEAICE_EXTERNAL.h                                        |
C     | o This file is for fields generated by the sea-ice       |
C     |   model, that are not in preexisting common block        |
C     |   variables, for example FFIELDS.h, and that may be      |
C     |   by other packages.
C     |==========================================================|
C     \==========================================================/
C
C     surfaceTendencyTice
C            - Temperature tendency in the top level due to the
C              melting or freezing of sea-ice.
C              Note that the surface level temperature is modified
C              directly by the sea-ice model in order to maintain
C              water temperature under sea-ice at the freezing
C              point.  But we need to keep track of the
C              equivalent amount of heat that this surface-level
C              temperature change implies because it is used by
C              the KPP package (kpp_calc.F and kpp_transport_t.F).
C              Units are degrees-C/s (>0 for ocean warming).
C
      COMMON /SEAICE_EXTERNAL/ surfaceTendencyTice
      _RS  surfaceTendencyTice(1-OLx:sNx+OLx,1-OLy:sNy+OLy,nSx,nSy)

#endif ALLOW_SEAICE
