#! /usr/bin/env bash

#  $Header: /u/gcmpack/MITgcm/verification/hs94.cs-32x32x5/input.impIGW/prepare_run,v 1.2 2011/02/22 16:55:53 jmc Exp $
#  $Name:  $
 
#- in order to save disc space, take grid files
#- from this dir:
fromDir="../../fizhi-cs-32x32x40/input"

fileList=`( cd $fromDir ; ls dxC1_dXYa.face00?.bin )`

#echo 'fileList=' $fileList

#- and do a symbolic link in the current directory 
#   (if the file does not already exist)
if test -d $fromDir ; then
  lnkList='files:'
  for xx in $fileList
  do
    if test -r ${fromDir}/$xx ; then 
      if test ! -r $xx ; then 
        lnkList=${lnkList}" "$xx
        ln -sf ${fromDir}/$xx .
      fi
    fi
  done
  echo ' link' $lnkList "from dir:" $fromDir
else
  echo " Error:" $fromDir "not a directory"
fi
