#!/bin/bash
#
# Generate make file dependency entries for TAF generated AD files
# passed as arguments
#

# process option arguments
CLEAN=
adfiles=
key_prev=
for key in "$@"; do
    if [[ -n "$key_prev" ]]; then
        eval "$key_prev=\$key"
        key_prev=
        continue
    fi

    case $key in
    -clean | --clean)
        CLEAN=true
        ;;
    -taf | --taf)
        key_prev="adfiles"
        ;;
    -*)
        echo "f90mkdepend_taf wrong key: $key"
        exit 1
        ;;
    *)
        # Append non-option arguments to adfiles
        adfiles="${adfiles:+$adfiles }$key"
        ;;
    esac
done

# don't complain if *.F90 doesn't match any files
shopt -s nullglob

# init files
log_file="f90mkdepend_taf.log"
dep_file="Makefile_taf.dep"

cat /dev/null > $log_file
cat /dev/null > $dep_file

# OPTION to clean Makefile of $dep_file
MAKEFILE=Makefile
if test -n "$CLEAN"; then
    if [[ $(tail -n 1 $MAKEFILE) == "include $dep_file" ]]; then
        head -n -1 $MAKEFILE > tmp && mv tmp $MAKEFILE
    fi
    rm -rf $dep_file $log_file
    exit 0
fi

# append module dependencies to Makefile
for filename in ${adfiles}; do
  # quick check for "use" to speed up processing
  if grep -iq '^ *use ' $filename; then
    # extract module name in lower case
    modreflist=$(grep -i '^ *use ' $filename | awk '{print tolower($2)}' | sed -e 's/,.*$//' -e 's/\r$//' | sort | uniq )

    echo "$filename => $modreflist" >> $log_file

    # determine AD suffix
    adsuff=$(echo ${filename%.*} | sed -e 's/.*_//')
    depline="$filename:"
    for m in $modreflist; do
	# I am sure that this can be shorter with only one grep command
	mm=$(grep -Hi "${m}$" ${adfiles} | grep -i module | grep -v end | awk -F: '{print $1}')
	if  [ $mm == $filename ] ; then
	    echo "INFO: f90mkdepend_taf: $filename contains module $m" 1>&2
        elif [[ ${#mm} > 0 ]] && [ -f ${mm} ] ; then
	    depline="$depline ${mm%.*}.o"
	else
            echo "WARNING: f90mkdepend_taf: in $filename no source file found for module $m" 1>&2
	fi
    done
    echo $depline >> $dep_file
  fi
done

echo "include $dep_file"
