#! /usr/bin/env bash

#-- Settings:
AWK=awk
keep=0;
if [ $# -ge 1 ] ; then
  if test $1 = '-help' -o $1 = '-h' ; then
    echo "Usage: `basename $0` [-k/-keep]"
    echo " suggest OPTFILE name for MITgcm 'genmake2' script"
    echo "options:"
    echo "  -h/-help :: just print this and return"
    echo "  -k/-keep :: keep log-file and temp-script file"
    exit
  fi
  if test $1 = '-keep' -o $1 = '-k' ; then keep=1 ; fi
fi
LOC_SH_FIND='find_optfile'
LOGFILE="$LOC_SH_FIND.log"
rm -f $LOC_SH_FIND $LOGFILE

#-- Get where to find MITgcm main dir (ROOTDIR):
if test "x$MITGCM_ROOTDIR" = x ; then
  if test "x$ROOTDIR" != x ; then
    echo "WARNING: Environment Variable 'ROOTDIR' no longer recognized"
    echo "WARNING:  use instead 'MITGCM_ROOTDIR'" ; ROOTDIR=
  fi
else
  ROOTDIR=$MITGCM_ROOTDIR
fi

#  Find the MITgcm ${ROOTDIR}
if test "x${ROOTDIR}" = x ; then
    tmp=`echo $PWD | sed -e 's/\// /g' | $AWK '{print $NR}'`
    if test "x$tmp" = "xbin" -a -d ../model -a -d ../eesupp -a -d ../pkg ; then
        ROOTDIR=".."
    else
        for d in . .. ../.. ../../.. ../../../.. ../../../../.. ; do
            if [ -d "$d/model" -a -d "$d/eesupp" -a -d "$d/pkg" ]; then
                ROOTDIR=$d
                printf "Warning: ROOTDIR was not specified ;"
                echo " try using a local copy of MITgcm found at \"$ROOTDIR\""
                break
            fi
        done
    fi
fi
if test "x${ROOTDIR}" = x ; then
    echo "Error: Cannot determine ROOTDIR for MITgcm code."
    echo "  Please specify a ROOTDIR using either the command line"
    echo "   option '-rootdir' or the Env.Var. 'MITGCM_ROOTDIR'."
    exit 1
fi
if test ! -d ${ROOTDIR} ; then
    echo "Error: the specified ROOTDIR (\"$ROOTDIR\") does not exist!"
    exit 1
fi

#---------------------------------------
#-- start to build script LOC_SH_FIND
#   by taking function "find_possible_optfile" from script "genmake2":

#head -n 1 $ROOTDIR/tools/genmake2 > $LOC_SH_FIND
sed -n '1 p' $ROOTDIR/tools/genmake2 >> $LOC_SH_FIND
echo '' >> $LOC_SH_FIND
#-- will improve this by using 1 or 2 special lines (to be added to genmake2)
sed -n '/^find_possible_optfile()/,/#  Just try to use FC, report/ p' \
          $ROOTDIR/tools/genmake2 >> $LOC_SH_FIND
echo '' >> $LOC_SH_FIND

cat >> $LOC_SH_FIND <<EOF
#-- Sequential part of script starts here ---------------
ROOTDIR=\$1
LOGFILE=\$2

find_possible_optfile

#echo "  The default optfile is:  "\$PLATFORM"_"\$FC

EOF

chmod 744 $LOC_SH_FIND
echo "-- running: './$LOC_SH_FIND $ROOTDIR $LOGFILE' :"
./$LOC_SH_FIND $ROOTDIR $LOGFILE

if test $keep = 0 ; then
  rm -r $LOC_SH_FIND $LOGFILE
fi
exit 0
