#! /usr/bin/env bash

# $Header: /u/gcmpack/MITgcm/tools/example_scripts/faulks/Attic/test_lcs,v 1.5 2007/01/15 03:22:41 edhill Exp $

#  Ed Hill

#  Test script for MITgcm that should work on most of the lcs.mit.edu
#  Linux machines.

usage()
{
    cat << EOF

Usage:  $0 [OPTIONS]

where possible OPTIONS are:
  (-help|-h)               print usage
  (-dir | -d) TDIR         specify testing directory
                             (def="$TDIR")
  (-of | -optfile) FILE    specify an OPTFILE
                             (def="$OPTFILE")
  (-[no]ieee)              IEEE math flag
                             (def="$IEEE")

EOF
    exit 1
}


# defaults
export PATH='/usr/local/bin:/bin:/usr/bin'
OPTFILE=
TESTDIR="/scratch2/edhill/test_"`hostname`
IEEE="-ieee"

#  Parse options
ac_prev=
for ac_option ; do

    # If the previous option needs an argument, assign it.
    if test -n "$ac_prev"; then
        eval "$ac_prev=\$ac_option"
        ac_prev=
        continue
    fi

    ac_optarg=`expr "x$ac_option" : 'x[^=]*=\(.*\)'`
    
    case $ac_option in
        
        -help | --help | -h | --h)
            usage ;;
        
        -dir | --dir | -d | --d)
            ac_prev=TESTDIR ;;
        -dir=* | --dir=* | -d=* | --d=*)
            TESTDIR=$ac_optarg ;;

        -of | --of | -optfile | --optfile)
            ac_prev=OPTFILE ;;
        --of=* | -of=* | --optfile=* | -optfile=*)
            OPTFILE=$ac_optarg ;;

	-ieee)
	    IEEE="-ieee" ;;
	-noieee)
	    IEEE= ;;
        
        *)
            echo "Error: don't understand argument \"$ac_option\""
            usage
            ;;
        
     esac
     
done

#  Turn off stack limit for FIZHI
ulimit -s unlimited

echo -n "Creating a temp directory ..."
mach=`hostname`
file=${OPTFILE##*/}
tdir=$TESTDIR"_"$file
test -e $tdir  &&  rm -rf $tdir
mkdir $tdir
echo "  done"

echo -n "Downloading the MITgcm code from CVS pserver..."
cd $tdir
export CVSROOT='/u/gcmpack'
cvs co -P MITgcm > /dev/null 2>&1
echo "  done"

new_dir='MITgcm_g77'
test -e $new_dir  &&  rm -rf $new_dir
mkdir $new_dir

  pushd $new_dir
  cp -ra ../MITgcm/* .
  echo "Running testreport using:"
  cd verification
  comm="./testreport $IEEE -a edhill@mitgcm.org"
  if test "x$OPTFILE" != x ; then
    comm="$comm -of=$OPTFILE"
  fi
  echo "  \"$comm\""
  echo "======================"
  echo
  $comm | tail -100
  popd

new_dir='MITgcm_ifort'
test -e $new_dir  &&  rm -rf $new_dir
mkdir $new_dir

  pushd $new_dir
  cp -ra ../MITgcm/* .
  echo "Running testreport using:"
  cd verification
  comm="./testreport $IEEE -of ../tools/build_options/linux_ia32_ifort -a edhill@mitgcm.org"
  echo "  \"$comm\""
  echo "======================"
  echo
  $comm | tail -100
  popd

new_dir='MITgcm_pgi'
test -e $new_dir  &&  rm -rf $new_dir
mkdir $new_dir

  pushd $new_dir
  cp -ra ../MITgcm/* .
  echo "Running testreport using:"
  export PGI=/usr/local/pkg/pgi/pgi-5.2-fc3
  cd verification
  comm="./testreport $IEEE -of ../tools/build_options/linux_ia32_pgf77+authors_fc3 -a edhill@mitgcm.org"
  echo "  \"$comm\""
  echo "======================"
  echo
  $comm | tail -100
  popd

new_dir='MITgcm_adm'
test -e $new_dir  &&  rm -rf $new_dir
mkdir $new_dir

  pushd $new_dir
  cp -ra ../MITgcm/* .
  echo "Running testreport using:"
  cd verification
  comm="./testreport -adm $IEEE -a edhill@mitgcm.org"
  if test "x$OPTFILE" != x ; then
    comm="$comm -of=$OPTFILE"
  fi
  echo "  \"$comm\""
  echo "======================"
  echo
  $comm | tail -100
  popd


