#! /usr/bin/env bash

# $Header: /u/gcmpack/MITgcm/tools/example_scripts/faulks/Attic/test_lcs_fc5,v 1.5 2006/07/18 18:24:20 edhill Exp $

#  Ed Hill

#  Test script for MITgcm that should work on most of the lcs.mit.edu
#  Linux machines.


# defaults
export PATH='/usr/local/bin:/bin:/usr/bin'
OPTFILE=
TESTDIR="/scratch/edhill/test_"`hostname`
IEEE="-ieee"


#  Turn off stack limit for FIZHI
ulimit -s unlimited

echo -n "Creating a temp directory ..."
mach=`hostname`
tdir=$TESTDIR
test -e $tdir  &&  rm -rf $tdir
mkdir $tdir
echo "  done"

echo -n "Downloading the MITgcm code from CVS pserver..."
cd $tdir
export CVSROOT='/u/gcmpack'
cvs co MITgcm > /dev/null 2>&1
echo "  done"
cd MITgcm/verification


echo "Running testreport using:"
comm="./testreport $IEEE -of ../tools/build_options/linux_ia32_g77 -a edhill@mitgcm.org"
echo "  \"$comm\""
echo "======================"
echo
$comm | tail -100

echo
echo "======================"
echo "Cleaning test directories:"
./testreport -clean > /dev/null 2>&1
echo "======================"
echo

echo "Running testreport using:"
comm="./testreport $IEEE -of ../tools/build_options/linux_ia32_gfortran -a edhill@mitgcm.org"
echo "  \"$comm\""
echo "======================"
echo
$comm | tail -100

echo
echo "======================"
echo "Cleaning test directories:"
./testreport -clean > /dev/null 2>&1
echo "======================"
echo

echo "Running testreport using:"
comm="./testreport $IEEE -of ../tools/build_options/linux_ia32_ifort+authors_v9 -a edhill@mitgcm.org"
echo "  \"$comm\""
echo "======================"
echo
$comm | tail -100

echo
echo "======================"
echo "Cleaning test directories:"
./testreport -clean > /dev/null 2>&1
echo "======================"
echo

echo "Running testreport using:"
export PGI=/usr/local/pkg/pgi/pgi-6.1-5
comm="./testreport $IEEE -of ../tools/build_options/linux_ia32_pgf77+authors_fc5 -a edhill@mitgcm.org"
echo "  \"$comm\""
echo "======================"
echo
$comm | tail -100

echo
echo "======================"
echo "Cleaning test directories:"
./testreport -clean > /dev/null 2>&1
echo "======================"
echo

echo "Running testreport using:"
comm="./testreport -adm $IEEE -of ../tools/build_options/linux_ia32_g77 -a edhill@mitgcm.org"
echo "  \"$comm\""
echo "======================"
echo
$comm | tail -100
 
echo
echo "======================"
echo "Cleaning test directories:"
./testreport -clean > /dev/null 2>&1
echo "======================"
echo

echo "Running testreport using:"
export OMP_NUM_THREADS=2
comm="./testreport -mth -of ../tools/build_options/linux_ia32_ifort.v9+mth"
echo "  \"$comm\""
echo "======================"
echo
$comm | tail -100
 
