#! /usr/bin/env bash

# $Header: /u/gcmpack/MITgcm/tools/example_scripts/faulks/Attic/test_csail,v 1.5 2007/03/26 20:53:42 jmc Exp $

#  Ed Hill

#  Test script for MITgcm that should work on most of the csail.mit.edu
#  Linux machines.


# defaults
export PATH='/usr/local/bin:/bin:/usr/bin'
OPTFILE=
TESTDIR="/scratch/jmc/test_"`hostname`
IEEE="-ieee"


#  Turn off stack limit for FIZHI
ulimit -s unlimited

echo -n "Creating a temp directory ..."
mach=`hostname`
tdir=$TESTDIR
if test -e $tdir
then test -e $tdir/MITgcm  &&  rm -rf $tdir/MITgcm
else mkdir $tdir
fi
echo "  done"

echo -n "Downloading the MITgcm code from CVS pserver..."
cd $tdir
#export CVSROOT='/u/gcmpack'
#export CVSROOT=':ext:@mitgcm.org:/u/gcmpack'
#export CVS_RSH='ssh'
#cvs co -P MITgcm > /dev/null
cvs -d :pserver:cvsanon@mitgcm.org:/u/gcmpack co -P MITgcm > /dev/null
echo "  done"

new_dir='MITgcm_g77'
test -e $new_dir  &&  rm -rf $new_dir
mkdir $new_dir

  pushd $new_dir
  cp -ra ../MITgcm/* .
  echo "Running testreport using:"
  cd verification
  comm="./testreport $IEEE -a edhill@mitgcm.org"
  if test "x$OPTFILE" != x ; then
    comm="$comm -of=$OPTFILE"
  fi
  echo "  \"$comm\""
  echo "======================"
  echo
  $comm | tail -100
  popd

new_dir='MITgcm_adm'
test -e $new_dir  &&  rm -rf $new_dir
mkdir $new_dir

  pushd $new_dir
  cp -ra ../MITgcm/* .
  echo "Running testreport using:"
  cd verification
  comm="./testreport -adm $IEEE -a edhill@mitgcm.org"
  if test "x$OPTFILE" != x ; then
    comm="$comm -of=$OPTFILE"
  fi
  echo "  \"$comm\""
  echo "======================"
  echo
  $comm | tail -100
  popd

new_dir='MITgcm_ifort'
test -e $new_dir  &&  rm -rf $new_dir
mkdir $new_dir

  pushd $new_dir
  cp -ra ../MITgcm/* .
  echo "Running testreport using:"
  cd verification
  comm="./testreport $IEEE -of ../tools/build_options/linux_ia32_ifort+authors_v9 -a edhill@mitgcm.org"
  echo "  \"$comm\""
  echo "======================"
  echo
  $comm | tail -100
  popd

new_dir='MITgcm_pgi'
test -e $new_dir  &&  rm -rf $new_dir
mkdir $new_dir

  pushd $new_dir
  cp -ra ../MITgcm/* .
  echo "Running testreport using:"
  export PGI=/usr/local/pkg/pgi/pgi-6.1-5
  cd verification
  comm="./testreport $IEEE -of ../tools/build_options/linux_ia32_pgf77+authors_fc5"
  echo "  \"$comm\""
  echo "======================"
  echo
  $comm | tail -100
  echo "Running testreport using:"
 #cd verification
  comm="./testreport $IEEE -of ../tools/build_options/linux_ia32_pgf77+authors_fc5 -a edhill@mitgcm.org -q"
  echo "  \"$comm\""
  echo "======================"
  echo
  $comm | tail -100
  popd
