#! /usr/bin/env bash

# $Header: /u/gcmpack/MITgcm/tools/example_scripts/faulks/Attic/test_csail,v 1.14 2007/12/26 14:52:50 jmc Exp $

#  Ed Hill

#  Test script for MITgcm that should work on most of the csail.mit.edu
#  Linux machines.


# defaults
export PATH='/usr/local/bin:/bin:/usr/bin'
OPTFILE=
TESTDIR="/scratch/jmc/test_"`hostname`
IEEE="-ieee"
MC=10


#  Turn off stack limit for FIZHI
ulimit -s unlimited

echo -n "Creating a temp directory ..."
mach=`hostname`
tdir=$TESTDIR
if test -e $tdir
then test -e $tdir/MITgcm  &&  rm -rf $tdir/MITgcm
else mkdir $tdir
fi
echo "  done"

#- clean-up old output files
rm -f $tdir/output_*

echo -n "Downloading the MITgcm code from CVS pserver..."
cd $tdir
#export CVSROOT='/u/gcmpack'
#export CVSROOT=':ext:@mitgcm.org:/u/gcmpack'
#export CVS_RSH='ssh'
#cvs co -P MITgcm > /dev/null
cvs -d :pserver:cvsanon@mitgcm.org:/u/gcmpack co -P MITgcm > /dev/null
echo "  done"

new_dir='MITgcm_g77'
test -e $new_dir  &&  rm -rf $new_dir
mkdir $new_dir

  echo "================================================================"
  pushd $new_dir
  cp -ra ../MITgcm/* .
  echo "Running testreport using:"
  cd verification
  comm="./testreport -a jmc@mitgcm.org"
  if test "x$OPTFILE" != x ; then
    comm="$comm -of=$OPTFILE"
  fi
  echo "  \"$comm\""
  echo "======================"
  $comm > $tdir/output_g77 2>&1
  tail -100 $tdir/output_g77
  echo
  popd

new_dir='MITgcm_adm'
test -e $new_dir  &&  rm -rf $new_dir
mkdir $new_dir

  echo "================================================================"
  pushd $new_dir
  cp -ra ../MITgcm/* .
  echo "Running testreport using:"
  cd verification
  comm="./testreport -adm -a jmc@mitgcm.org"
  if test "x$OPTFILE" != x ; then
    comm="$comm -of=$OPTFILE"
  fi
  echo "  \"$comm\""
  echo "======================"
  $comm > $tdir/output_adm 2>&1
  tail -60 $tdir/output_adm
  echo
  popd

new_dir='MITgcm_ifort'
test -e $new_dir  &&  rm -rf $new_dir
mkdir $new_dir

  echo "================================================================"
  pushd $new_dir
  cp -ra ../MITgcm/* .
  echo "Running testreport using:"
  cd verification
  comm="./testreport -match $MC -of ../tools/build_options/linux_ia32_ifort+authors_v9 -a jmc@mitgcm.org"
  echo "  \"$comm\""
  echo "======================"
  $comm > $tdir/output_ifc 2>&1
  tail -100 $tdir/output_ifc
  echo
#-- also test restart (test 2+2=4)
  echo "testing restart using:"
  comm="../tools/do_tst_2+2 -a jmc@mitgcm.org"
  echo "  \"$comm\""
  echo "======================"
  $comm > $tdir/output_2+2 2>&1
# tail -100 $tdir/output_2+2
  echo ; cat tst_2+2_out.txt
  echo
  popd

new_dir='MITgcm_pgi'
test -e $new_dir  &&  rm -rf $new_dir
mkdir $new_dir

  echo "================================================================"
  pushd $new_dir
  cp -ra ../MITgcm/* .
  echo "Running testreport using:"
  export PGI=/usr/local/pkg/pgi/pgi-6.1-5
  cd verification
  comm="./testreport -match $MC -of ../tools/build_options/linux_ia32_pgf77+authors_fc5 -dd"
  echo "  \"$comm\""
  echo "======================"
  $comm > $tdir/output_pgi_1 2>&1
  tail -100 $tdir/output_pgi_1
  echo
  echo "Running testreport using:"
 #cd verification
  comm="./testreport -match $MC -of ../tools/build_options/linux_ia32_pgf77+authors_fc5 -a jmc@mitgcm.org -q"
  echo "  \"$comm\""
  echo "======================"
  $comm > $tdir/output_pgi_2 2>&1
  tail -100 $tdir/output_pgi_2
  echo
  popd
