#! /usr/bin/env bash

#  $Header: /u/gcmpack/MITgcm/verification/offline_exf_seaice/input.seaice/Attic/prepare_run,v 1.1 2011/12/22 15:18:03 mlosch Exp $
#  $Name:  $
 
#- in order to save disc space, take *.bin files
#- from this dir:
fromDir="../../lab_sea/input"

fileList=`( cd $fromDir ; echo *79 )`

#echo 'fileList=' $fileList

#- and do a symbolic link in the current directory 
#   (if the file does not already exist)
if test -d $fromDir ; then
  lnkList='files:'
  for xx in $fileList
  do
    if test -r ${fromDir}/$xx ; then 
      if test ! -r $xx ; then 
        lnkList=${lnkList}" "$xx
        ln -sf ${fromDir}/$xx .
      fi
    fi
  done
  echo ' link' $lnkList "from dir:" $fromDir
else
  echo " Error:" $fromDir "not a directory"
fi
