#! /usr/bin/env bash

#  $Header: /u/gcmpack/MITgcm/verification/global_ocean.cs32x15/input.viscA4/prepare_run,v 1.1 2006/07/16 03:41:25 jmc Exp $
#  $Name:  $
 
#- in order to save disc space, un-gzip files
#- from this dir:
fromDir="../input.viscA4"

fileList=`( cd $fromDir ; echo *.gz | sed 's/\.gz//g' )`

#echo 'fileList=' $fileList

#- copy the gz file in the current directory and unzip 
#   (if the file does not already exist)
if test -d $fromDir ; then
  lnkList='files:'
  for xx in $fileList
  do
    if test -r ${xx}.gz ; then 
      if test ! -r $xx ; then 
        lnkList=${lnkList}" "$xx
        gunzip -f ${xx}.gz
      fi
    fi
  done
#-- a trick to rename pickup by making a symbolic link in the current directory
      xx='pickup.0000086400'
      yy='pickup.0000072000'
      if test ! -r $xx ; then 
        lnkList=${lnkList}" "$xx
        ln -sf $yy $xx
      fi
#------
  echo ' unzip' $lnkList
else
  echo " Error:" $fromDir "not a directory"
fi
