#!/bin/csh

# LoadLeveler batch commands that are used if this script is submitted to
#   the share batch queue:
#@output=out
#@error=err
#@class=share

#@job_type=parallel
#@node=1
#@network.MPI=csss,shared,us
#@queue

cd ~/tmp/MITgcm/verification
bash ./testreport -bash /usr/bin/bash -make gmake -of=../tools/build_options/sp4 


